"""
字段定义 - agent 分类
从 config_registry.py 按 category 拆分
"""

FIELD_DEFINITIONS: dict = {
    "AGENT_MODE": {       'category': 'agent',
        'data_type': 'boolean',
        'default_value': 'false',
        'description': 'Enable ReAct Agent for stock analysis.',
        'display_order': 10,
        'docs': [       {       'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/full-guide.md#环境变量完整列表',
                                'label': '完整指南：Agent 配置'}],
        'examples': ['AGENT_MODE=true', 'AGENT_MODE=false'],
        'help_key': 'settings.agent.AGENT_MODE',
        'is_editable': True,
        'is_required': False,
        'is_sensitive': False,
        'options': [],
        'title': 'Agent Mode',
        'ui_control': 'switch',
        'validation': {},
        'warning_codes': []},
    "AGENT_MAX_STEPS": {       'category': 'agent',
        'data_type': 'integer',
        'default_value': '10',
        'description': 'Maximum reasoning-step limit for Agent mode. At the default (10), each sub-agent keeps its own '
                       'preset. When raised above 10, all sub-agents adopt this value. When lowered below a '
                       "sub-agent's preset, that sub-agent is capped at this value.",
        'display_order': 20,
        'docs': [       {       'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/full-guide.md#环境变量完整列表',
                                'label': '完整指南：Agent 配置'}],
        'examples': ['AGENT_MAX_STEPS=10', 'AGENT_MAX_STEPS=25'],
        'help_key': 'settings.agent.AGENT_MAX_STEPS',
        'is_editable': True,
        'is_required': False,
        'is_sensitive': False,
        'options': [],
        'title': 'Agent Max Steps',
        'ui_control': 'number',
        'validation': {'max': 50, 'min': 1},
        'warning_codes': []},
    "AGENT_SKILLS": {       'category': 'agent',
        'data_type': 'string',
        'default_value': '',
        'description': 'Comma-separated list of active agent strategy skills. Leave empty to use the primary default '
                       'strategy skill declared in metadata (built-in default: bull_trend). When set to specific '
                       "skills (not 'all'), scheduled tasks will automatically use the Agent pipeline.",
        'display_order': 30,
        'docs': [       {       'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/full-guide.md#环境变量完整列表',
                                'label': '完整指南：Agent 配置'}],
        'examples': ['AGENT_SKILLS=', 'AGENT_SKILLS=bull_trend,mean_reversion', 'AGENT_SKILLS=all'],
        'help_key': 'settings.agent.AGENT_SKILLS',
        'is_editable': True,
        'is_required': False,
        'is_sensitive': False,
        'options': [],
        'title': 'Agent Strategies',
        'ui_control': 'text',
        'validation': {},
        'warning_codes': []},
    "AGENT_SKILL_DIR": {       'category': 'agent',
        'data_type': 'string',
        'default_value': 'strategies',
        'description': 'Directory containing agent strategy-skill definition files (YAML or SKILL.md bundles).',
        'display_order': 40,
        'docs': [       {       'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/full-guide.md#环境变量完整列表',
                                'label': '完整指南：Agent 配置'}],
        'examples': ['AGENT_SKILL_DIR=strategies', 'AGENT_SKILL_DIR=my_strategies'],
        'help_key': 'settings.agent.AGENT_SKILL_DIR',
        'is_editable': True,
        'is_required': False,
        'is_sensitive': False,
        'options': [],
        'title': 'Agent Strategy Dir',
        'ui_control': 'text',
        'validation': {},
        'warning_codes': []},
    "AGENT_NL_ROUTING": {       'category': 'agent',
        'data_type': 'boolean',
        'default_value': 'false',
        'description': 'Enable natural-language routing in bot dispatcher. When on, high-confidence stock queries in '
                       'private chat (or @mentions) are routed to the agent even without an explicit command.',
        'display_order': 50,
        'docs': [       {       'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/full-guide.md#环境变量完整列表',
                                'label': '完整指南：Agent 配置'}],
        'examples': ['AGENT_NL_ROUTING=true', 'AGENT_NL_ROUTING=false'],
        'help_key': 'settings.agent.AGENT_NL_ROUTING',
        'is_editable': True,
        'is_required': False,
        'is_sensitive': False,
        'options': [],
        'title': 'Agent NL Routing',
        'ui_control': 'switch',
        'validation': {},
        'warning_codes': []},
    "AGENT_ARCH": {       'category': 'agent',
        'data_type': 'string',
        'default_value': 'single',
        'description': "Agent execution architecture. 'single' uses the classic ReAct executor; 'multi' uses the "
                       'orchestrator pipeline with specialised sub-agents.',
        'display_order': 60,
        'docs': [       {       'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/full-guide.md#环境变量完整列表',
                                'label': '完整指南：Agent 配置'}],
        'examples': ['AGENT_ARCH=single', 'AGENT_ARCH=multi'],
        'help_key': 'settings.agent.AGENT_ARCH',
        'is_editable': True,
        'is_required': False,
        'is_sensitive': False,
        'options': [       {'label': 'Single Agent', 'value': 'single'},
                           {'label': 'Multi Agent (Orchestrator)', 'value': 'multi'}],
        'title': 'Agent Architecture',
        'ui_control': 'select',
        'validation': {},
        'warning_codes': []},
    "AGENT_ORCHESTRATOR_MODE": {       'category': 'agent',
        'data_type': 'string',
        'default_value': 'standard',
        'description': "Pipeline mode when AGENT_ARCH=multi. 'quick' (tech→decision), 'standard' "
                       "(tech→intel→decision), 'full' (tech→intel→risk→decision), 'specialist' (full + per-strategy "
                       'specialist agents).',
        'display_order': 61,
        'docs': [       {       'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/full-guide.md#环境变量完整列表',
                                'label': '完整指南：Agent 配置'}],
        'examples': ['AGENT_ORCHESTRATOR_MODE=standard', 'AGENT_ORCHESTRATOR_MODE=full'],
        'help_key': 'settings.agent.AGENT_ORCHESTRATOR_MODE',
        'is_editable': True,
        'is_required': False,
        'is_sensitive': False,
        'options': [       {'label': 'Quick', 'value': 'quick'},
                           {'label': 'Standard', 'value': 'standard'},
                           {'label': 'Full', 'value': 'full'},
                           {'label': 'Specialist', 'value': 'specialist'}],
        'title': 'Orchestrator Mode',
        'ui_control': 'select',
        'validation': {'enum': ['quick', 'standard', 'full', 'specialist', 'strategy', 'skill']},
        'warning_codes': []},
    "AGENT_ORCHESTRATOR_TIMEOUT_S": {       'category': 'agent',
        'data_type': 'integer',
        'default_value': '600',
        'description': 'Shared timeout budget in seconds for Agent execution. Single-agent runs use it as the overall '
                       'ReAct loop budget; multi-agent mode uses it as the cooperative pipeline budget. Set to 0 to '
                       'disable.',
        'display_order': 62,
        'docs': [       {       'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/full-guide.md#环境变量完整列表',
                                'label': '完整指南：Agent 配置'}],
        'examples': ['AGENT_ORCHESTRATOR_TIMEOUT_S=600', 'AGENT_ORCHESTRATOR_TIMEOUT_S=0'],
        'help_key': 'settings.agent.AGENT_ORCHESTRATOR_TIMEOUT_S',
        'is_editable': True,
        'is_required': False,
        'is_sensitive': False,
        'options': [],
        'title': 'Agent Timeout',
        'ui_control': 'number',
        'validation': {'max': 3600, 'min': 0},
        'warning_codes': []},
    "AGENT_RISK_OVERRIDE": {       'category': 'agent',
        'data_type': 'boolean',
        'default_value': 'true',
        'description': 'Allow the risk agent to veto buy signals when critical risk flags are detected.',
        'display_order': 63,
        'docs': [       {       'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/full-guide.md#环境变量完整列表',
                                'label': '完整指南：Agent 配置'}],
        'examples': ['AGENT_RISK_OVERRIDE=true', 'AGENT_RISK_OVERRIDE=false'],
        'help_key': 'settings.agent.AGENT_RISK_OVERRIDE',
        'is_editable': True,
        'is_required': False,
        'is_sensitive': False,
        'options': [],
        'title': 'Risk Agent Override',
        'ui_control': 'switch',
        'validation': {},
        'warning_codes': []},
    "AGENT_DEEP_RESEARCH_BUDGET": {       'category': 'agent',
        'data_type': 'integer',
        'default_value': '30000',
        'description': 'Maximum token budget for Deep Research planning, follow-up research, and final synthesis.',
        'display_order': 64,
        'docs': [       {       'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/full-guide.md#环境变量完整列表',
                                'label': '完整指南：Agent 配置'}],
        'examples': ['AGENT_DEEP_RESEARCH_BUDGET=30000', 'AGENT_DEEP_RESEARCH_BUDGET=50000'],
        'help_key': 'settings.agent.DEEP_RESEARCH',
        'is_editable': True,
        'is_required': False,
        'is_sensitive': False,
        'options': [],
        'title': 'Deep Research Token Budget',
        'ui_control': 'number',
        'validation': {'max': 100000, 'min': 5000},
        'warning_codes': []},
    "AGENT_DEEP_RESEARCH_TIMEOUT": {       'category': 'agent',
        'data_type': 'integer',
        'default_value': '180',
        'description': 'Maximum seconds allowed for a Deep Research request before returning a timeout response.',
        'display_order': 65,
        'docs': [       {       'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/full-guide.md#环境变量完整列表',
                                'label': '完整指南：Agent 配置'}],
        'examples': ['AGENT_DEEP_RESEARCH_TIMEOUT=180', 'AGENT_DEEP_RESEARCH_TIMEOUT=300'],
        'help_key': 'settings.agent.DEEP_RESEARCH',
        'is_editable': True,
        'is_required': False,
        'is_sensitive': False,
        'options': [],
        'title': 'Deep Research Timeout',
        'ui_control': 'number',
        'validation': {'max': 600, 'min': 30},
        'warning_codes': []},
    "AGENT_MEMORY_ENABLED": {       'category': 'agent',
        'data_type': 'boolean',
        'default_value': 'false',
        'description': 'Enable the memory & calibration system. Tracks prediction accuracy and adjusts agent '
                       'confidence over time.',
        'display_order': 66,
        'docs': [       {       'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/full-guide.md#环境变量完整列表',
                                'label': '完整指南：Agent 配置'}],
        'examples': ['AGENT_MEMORY_ENABLED=true', 'AGENT_MEMORY_ENABLED=false'],
        'help_key': 'settings.agent.AGENT_MEMORY_ENABLED',
        'is_editable': True,
        'is_required': False,
        'is_sensitive': False,
        'options': [],
        'title': 'Agent Memory',
        'ui_control': 'switch',
        'validation': {},
        'warning_codes': []},
    "AGENT_SKILL_AUTOWEIGHT": {       'category': 'agent',
        'data_type': 'boolean',
        'default_value': 'true',
        'description': 'Automatically weight strategy-skill opinions by their historical backtest performance.',
        'display_order': 67,
        'docs': [       {       'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/full-guide.md#环境变量完整列表',
                                'label': '完整指南：Agent 配置'}],
        'examples': ['AGENT_SKILL_AUTOWEIGHT=true', 'AGENT_SKILL_AUTOWEIGHT=false'],
        'help_key': 'settings.agent.AGENT_SKILL_AUTOWEIGHT',
        'is_editable': True,
        'is_required': False,
        'is_sensitive': False,
        'options': [],
        'title': 'Auto-Weight Strategies',
        'ui_control': 'switch',
        'validation': {},
        'warning_codes': []},
    "AGENT_SKILL_ROUTING": {       'category': 'agent',
        'data_type': 'string',
        'default_value': 'auto',
        'description': "Strategy-skill selection mode. 'auto' detects market regime and picks relevant skills; "
                       "'manual' uses AGENT_SKILLS list only.",
        'display_order': 68,
        'docs': [       {       'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/full-guide.md#环境变量完整列表',
                                'label': '完整指南：Agent 配置'}],
        'examples': ['AGENT_SKILL_ROUTING=auto', 'AGENT_SKILL_ROUTING=manual'],
        'help_key': 'settings.agent.AGENT_SKILL_ROUTING',
        'is_editable': True,
        'is_required': False,
        'is_sensitive': False,
        'options': [       {'label': 'Auto (Regime-based)', 'value': 'auto'},
                           {'label': 'Manual (Use AGENT_SKILLS)', 'value': 'manual'}],
        'title': 'Strategy Routing',
        'ui_control': 'select',
        'validation': {},
        'warning_codes': []},
    "AGENT_CONTEXT_COMPRESSION_ENABLED": {       'category': 'agent',
        'data_type': 'boolean',
        'default_value': 'false',
        'description': 'Enable rolling compression of visible Agent chat history. Default is off to preserve existing '
                       'behavior.',
        'display_order': 72,
        'docs': [       {       'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/LLM_CONFIG_GUIDE.md#问股可见对话上下文压缩',
                                'label': 'LLM 配置指南：问股可见对话上下文压缩'},
                        {       'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/full-guide.md#环境变量完整列表',
                                'label': '完整指南：环境变量完整列表'}],
        'examples': ['AGENT_CONTEXT_COMPRESSION_ENABLED=false', 'AGENT_CONTEXT_COMPRESSION_ENABLED=true'],
        'help_key': 'settings.agent.context_compression',
        'is_editable': True,
        'is_required': False,
        'is_sensitive': False,
        'options': [],
        'title': 'Agent Context Compression',
        'ui_control': 'switch',
        'validation': {},
        'warning_codes': []},
    "AGENT_CONTEXT_COMPRESSION_PROFILE": {       'category': 'agent',
        'data_type': 'string',
        'default_value': 'balanced',
        'description': 'Preset for visible chat history compression. Trigger/protected-turn fields can be left empty '
                       'to follow the selected profile.',
        'display_order': 73,
        'docs': [       {       'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/LLM_CONFIG_GUIDE.md#问股可见对话上下文压缩',
                                'label': 'LLM 配置指南：问股可见对话上下文压缩'},
                        {       'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/full-guide.md#环境变量完整列表',
                                'label': '完整指南：环境变量完整列表'}],
        'examples': [       'AGENT_CONTEXT_COMPRESSION_PROFILE=balanced',
                            'AGENT_CONTEXT_COMPRESSION_PROFILE=cost',
                            'AGENT_CONTEXT_COMPRESSION_PROFILE=long_context_raw_first'],
        'help_key': 'settings.agent.context_compression',
        'is_editable': True,
        'is_required': False,
        'is_sensitive': False,
        'options': [       {'label': '成本优先', 'value': 'cost'},
                           {'label': '均衡推荐', 'value': 'balanced'},
                           {'label': '长上下文原文优先', 'value': 'long_context_raw_first'}],
        'title': 'Context Compression Profile',
        'ui_control': 'select',
        'validation': {'enum': ['cost', 'balanced', 'long_context_raw_first']},
        'warning_codes': []},
    "AGENT_CONTEXT_COMPRESSION_TRIGGER_TOKENS": {       'category': 'agent',
        'data_type': 'integer',
        'default_value': '',
        'description': 'Token threshold for visible chat history compression. Leave empty to follow the selected '
                       'compression profile preset.',
        'display_order': 74,
        'docs': [       {       'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/LLM_CONFIG_GUIDE.md#问股可见对话上下文压缩',
                                'label': 'LLM 配置指南：问股可见对话上下文压缩'},
                        {       'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/full-guide.md#环境变量完整列表',
                                'label': '完整指南：环境变量完整列表'}],
        'examples': ['AGENT_CONTEXT_COMPRESSION_TRIGGER_TOKENS=', 'AGENT_CONTEXT_COMPRESSION_TRIGGER_TOKENS=12000'],
        'help_key': 'settings.agent.context_compression',
        'is_editable': True,
        'is_required': False,
        'is_sensitive': False,
        'options': [],
        'title': 'Context Compression Trigger Tokens',
        'ui_control': 'number',
        'validation': {'max': 200000, 'min': 1000},
        'warning_codes': []},
    "AGENT_CONTEXT_PROTECTED_TURNS": {       'category': 'agent',
        'data_type': 'integer',
        'default_value': '',
        'description': 'Recent user turns preserved verbatim during visible chat history compression. Leave empty to '
                       'follow the selected compression profile preset.',
        'display_order': 75,
        'docs': [       {       'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/LLM_CONFIG_GUIDE.md#问股可见对话上下文压缩',
                                'label': 'LLM 配置指南：问股可见对话上下文压缩'},
                        {       'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/full-guide.md#环境变量完整列表',
                                'label': '完整指南：环境变量完整列表'}],
        'examples': ['AGENT_CONTEXT_PROTECTED_TURNS=', 'AGENT_CONTEXT_PROTECTED_TURNS=4'],
        'help_key': 'settings.agent.context_compression',
        'is_editable': True,
        'is_required': False,
        'is_sensitive': False,
        'options': [],
        'title': 'Context Protected Turns',
        'ui_control': 'number',
        'validation': {'max': 20, 'min': 1},
        'warning_codes': []},
    "AGENT_EVENT_MONITOR_ENABLED": {       'category': 'agent',
        'data_type': 'boolean',
        'default_value': 'false',
        'description': 'Enable background Event Monitor polling in schedule mode.',
        'display_order': 69,
        'docs': [       {       'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/alerts.md',
                                'label': '告警中心文档'}],
        'examples': ['AGENT_EVENT_MONITOR_ENABLED=true', 'AGENT_EVENT_MONITOR_INTERVAL_MINUTES=5'],
        'help_key': 'settings.agent.event_monitor',
        'is_editable': True,
        'is_required': False,
        'is_sensitive': False,
        'options': [],
        'title': 'Event Monitor',
        'ui_control': 'switch',
        'validation': {},
        'warning_codes': []},
    "AGENT_EVENT_MONITOR_INTERVAL_MINUTES": {       'category': 'agent',
        'data_type': 'integer',
        'default_value': '5',
        'description': 'Polling interval, in minutes, for background Event Monitor checks.',
        'display_order': 70,
        'docs': [       {       'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/alerts.md',
                                'label': '告警中心文档'}],
        'examples': ['AGENT_EVENT_MONITOR_INTERVAL_MINUTES=5', 'AGENT_EVENT_MONITOR_INTERVAL_MINUTES=15'],
        'help_key': 'settings.agent.event_monitor',
        'is_editable': True,
        'is_required': False,
        'is_sensitive': False,
        'options': [],
        'title': 'Event Monitor Interval',
        'ui_control': 'number',
        'validation': {'max': 1440, 'min': 1},
        'warning_codes': []},
    "AGENT_EVENT_ALERT_RULES_JSON": {       'category': 'agent',
        'data_type': 'json',
        'default_value': '',
        'description': 'JSON array of Event Monitor rules loaded by schedule mode. Legacy JSON supports only '
                       'price_cross, price_change_percent, and volume_spike. Technical indicator, watchlist, '
                       'portfolio, and market light alert rules are available through the Alert API/Web center.',
        'display_order': 71,
        'docs': [       {       'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/alerts.md',
                                'label': '告警中心文档'}],
        'examples': [       'AGENT_EVENT_ALERT_RULES_JSON=[{"alert_type":"price_cross","stock_code":"600519","direction":"above","price":1800}]',
                            'AGENT_EVENT_ALERT_RULES_JSON=[{"alert_type":"volume_spike","stock_code":"300750","multiplier":2.5}]'],
        'help_key': 'settings.agent.EVENT_ALERT_RULES_JSON',
        'is_editable': True,
        'is_required': False,
        'is_sensitive': False,
        'options': [],
        'title': 'Event Alert Rules',
        'ui_control': 'textarea',
        'validation': {},
        'warning_codes': ['legacy_json_only_basic_rules']}
}
