"""
字段定义 - ai_model 分类
从 config_registry.py 按 category 拆分
"""

FIELD_DEFINITIONS: dict = {
    "LITELLM_MODEL": {       'category': 'ai_model',
        'data_type': 'string',
        'default_value': None,
        'description': 'Primary model in provider/model format (e.g. gemini/gemini-3.1-pro-preview, '
                       'deepseek/deepseek-v4-flash, anthropic/claude-sonnet-4-6). If empty, it is auto-inferred from '
                       'available API keys or channel declarations.',
        'display_order': 1,
        'docs': [       {       'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/LLM_CONFIG_GUIDE.md',
                                'label': 'LLM 配置指南'},
                        {       'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/full-guide.md#ai-模型配置',
                                'label': '完整指南：AI 模型配置'}],
        'examples': [       'LITELLM_MODEL=deepseek/deepseek-v4-flash',
                            'LITELLM_MODEL=gemini/gemini-3.1-pro-preview',
                            'LITELLM_MODEL=ollama/qwen3:8b'],
        'help_key': 'settings.ai_model.LITELLM_MODEL',
        'is_editable': True,
        'is_required': False,
        'is_sensitive': False,
        'options': [],
        'title': 'Primary Model',
        'ui_control': 'text',
        'validation': {},
        'warning_codes': ['provider_prefix_required']},
    "AGENT_LITELLM_MODEL": {       'category': 'ai_model',
        'data_type': 'string',
        'default_value': None,
        'description': 'Optional Agent-only primary model in provider/model format. When empty, Agent inherits the '
                       'primary model. Bare model names are normalized to openai/<model>.',
        'display_order': 2,
        'docs': [       {       'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/LLM_CONFIG_GUIDE.md',
                                'label': 'LLM 配置指南'},
                        {       'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/full-guide.md#ai-模型配置',
                                'label': '完整指南：AI 模型配置'}],
        'examples': [       'AGENT_LITELLM_MODEL=deepseek/deepseek-v4-pro',
                            'AGENT_LITELLM_MODEL=gemini/gemini-3.1-pro-preview'],
        'help_key': 'settings.ai_model.AGENT_LITELLM_MODEL',
        'is_editable': True,
        'is_required': False,
        'is_sensitive': False,
        'options': [],
        'title': 'Agent Primary Model',
        'ui_control': 'text',
        'validation': {},
        'warning_codes': ['inherits_primary_when_empty']},
    "LITELLM_FALLBACK_MODELS": {       'category': 'ai_model',
        'data_type': 'string',
        'default_value': None,
        'description': 'Comma-separated fallback models tried when the primary model fails (e.g. '
                       'anthropic/claude-sonnet-4-6,openai/gpt-5.4-mini). Useful for cross-provider redundancy.',
        'display_order': 2,
        'docs': [       {       'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/LLM_CONFIG_GUIDE.md',
                                'label': 'LLM 配置指南'},
                        {       'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/full-guide.md#ai-模型配置',
                                'label': '完整指南：AI 模型配置'}],
        'examples': [       'LITELLM_FALLBACK_MODELS=deepseek/deepseek-v4-pro,gemini/gemini-3-flash-preview',
                            'LITELLM_FALLBACK_MODELS=openai/gpt-5.4-mini'],
        'help_key': 'settings.ai_model.LITELLM_FALLBACK_MODELS',
        'is_editable': True,
        'is_required': False,
        'is_sensitive': False,
        'options': [],
        'title': 'Fallback Models',
        'ui_control': 'text',
        'validation': {},
        'warning_codes': ['fallback_models_must_be_available']},
    "LITELLM_CONFIG": {       'category': 'ai_model',
        'data_type': 'string',
        'default_value': None,
        'description': 'Path to an advanced model routing YAML file (expert use). When valid/parseable and yields a '
                       'model_list, it takes priority over channels and legacy keys; otherwise channels/legacy are '
                       'used as fallback.',
        'display_order': 3,
        'docs': [       {       'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/LLM_CONFIG_GUIDE.md#方式三litellm-原生-yaml-配置适合专家或复杂路由',
                                'label': 'LLM 配置指南：YAML 模式'}],
        'examples': ['LITELLM_CONFIG=./litellm_config.yaml'],
        'help_key': 'settings.ai_model.LITELLM_CONFIG',
        'is_editable': True,
        'is_required': False,
        'is_sensitive': False,
        'options': [],
        'title': 'Advanced Model Routing Config',
        'ui_control': 'text',
        'validation': {},
        'warning_codes': ['yaml_config_overrides_channel_editor']},
    "LLM_CHANNELS": {       'category': 'ai_model',
        'data_type': 'string',
        'default_value': None,
        'description': 'Channel names (comma-separated). Managed by the channel editor above.',
        'display_order': 4,
        'docs': [       {       'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/LLM_CONFIG_GUIDE.md#方式二渠道channels模式配置适合进阶多模型',
                                'label': 'LLM 配置指南：渠道模式'},
                        {       'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/llm-providers.md',
                                'label': 'LLM 服务商配置速查'}],
        'examples': [       'LLM_CHANNELS=deepseek,aihubmix',
                            'LLM_DEEPSEEK_BASE_URL=https://api.deepseek.com',
                            'LLM_DEEPSEEK_API_KEY=sk-xxxx',
                            'LLM_DEEPSEEK_MODELS=deepseek-v4-flash,deepseek-v4-pro'],
        'help_key': 'settings.ai_model.LLM_CHANNELS',
        'is_editable': True,
        'is_required': False,
        'is_sensitive': False,
        'options': [],
        'title': 'LLM Channels',
        'ui_control': 'text',
        'validation': {},
        'warning_codes': ['channels_override_legacy_keys']},
    "LLM_TEMPERATURE": {       'category': 'ai_model',
        'data_type': 'number',
        'default_value': '0.7',
        'description': 'Unified sampling temperature for all LLM calls. Range [0.0, 2.0], default 0.7.',
        'display_order': 5,
        'docs': [       {       'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/full-guide.md#ai-模型配置',
                                'label': '完整指南：AI 模型配置'}],
        'examples': ['LLM_TEMPERATURE=0.2', 'LLM_TEMPERATURE=0.7'],
        'help_key': 'settings.ai_model.LLM_TEMPERATURE',
        'is_editable': True,
        'is_required': False,
        'is_sensitive': False,
        'options': [],
        'title': 'Temperature',
        'ui_control': 'number',
        'validation': {'max': 2.0, 'min': 0.0},
        'warning_codes': []},
    "AIHUBMIX_KEY": {       'category': 'ai_model',
        'data_type': 'string',
        'default_value': None,
        'description': 'AIHubmix one-stop API key – access all mainstream models with a single key, no VPN required. '
                       'Auto-sets base URL to aihubmix.com/v1. Get key: https://aihubmix.com/?aff=CfMq',
        'display_order': 5,
        'docs': [       {       'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/LLM_CONFIG_GUIDE.md',
                                'label': 'LLM 配置指南'},
                        {       'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/llm-providers.md',
                                'label': 'LLM 服务商配置速查'}],
        'examples': ['AIHUBMIX_KEY=sk-xxxx'],
        'help_key': 'settings.ai_model.provider_keys',
        'is_editable': True,
        'is_required': False,
        'is_sensitive': True,
        'options': [],
        'title': 'AIHubmix Key',
        'ui_control': 'password',
        'validation': {},
        'warning_codes': ['secret_value']},
    "ANSPIRE_LLM_ENABLED": {       'category': 'ai_model',
        'data_type': 'boolean',
        'default_value': 'true',
        'description': 'Use ANSPIRE_API_KEYS as an OpenAI-compatible Anspire LLM key when no higher-priority LLM '
                       'channel or OpenAI-compatible key is configured.',
        'display_order': 6,
        'is_editable': True,
        'is_required': False,
        'is_sensitive': False,
        'options': [],
        'title': 'Anspire LLM Enabled',
        'ui_control': 'switch',
        'validation': {}},
    "ANSPIRE_LLM_BASE_URL": {       'category': 'ai_model',
        'data_type': 'string',
        'default_value': 'https://open-gateway.anspire.cn/v6',
        'description': 'Anspire OpenAI-compatible gateway. Default: https://open-gateway.anspire.cn/v6; global '
                       'endpoint: https://open-gateway.anspire.ai/v6.',
        'display_order': 7,
        'is_editable': True,
        'is_required': False,
        'is_sensitive': False,
        'options': [],
        'title': 'Anspire LLM Base URL',
        'ui_control': 'text',
        'validation': {'format': 'url'}},
    "ANSPIRE_LLM_MODEL": {       'category': 'ai_model',
        'data_type': 'string',
        'default_value': 'Doubao-Seed-2.0-lite',
        'description': 'Default model used when ANSPIRE_API_KEYS enables the Anspire LLM gateway without an explicit '
                       'LITELLM_MODEL.',
        'display_order': 8,
        'is_editable': True,
        'is_required': False,
        'is_sensitive': False,
        'options': [],
        'title': 'Anspire LLM Model',
        'ui_control': 'text',
        'validation': {}},
    "DEEPSEEK_API_KEY": {       'category': 'ai_model',
        'data_type': 'string',
        'default_value': None,
        'description': 'Official DeepSeek API key (from https://platform.deepseek.com). For compatibility, a key set '
                       'alone still auto-infers deepseek/deepseek-chat and logs a deprecation warning; new configs '
                       'should migrate to deepseek/deepseek-v4-flash. Also works in multi-channel mode.',
        'display_order': 6,
        'docs': [       {       'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/LLM_CONFIG_GUIDE.md',
                                'label': 'LLM 配置指南'},
                        {       'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/llm-providers.md',
                                'label': 'LLM 服务商配置速查'}],
        'examples': ['DEEPSEEK_API_KEY=sk-xxxx', 'LITELLM_MODEL=deepseek/deepseek-v4-flash'],
        'help_key': 'settings.ai_model.provider_keys',
        'is_editable': True,
        'is_required': False,
        'is_sensitive': True,
        'options': [],
        'title': 'DeepSeek API Key',
        'ui_control': 'password',
        'validation': {},
        'warning_codes': ['secret_value']},
    "DEEPSEEK_API_KEYS": {       'category': 'ai_model',
        'data_type': 'string',
        'default_value': None,
        'description': 'Comma-separated DeepSeek API keys for load balancing. Takes priority over DEEPSEEK_API_KEY.',
        'display_order': 7,
        'is_editable': True,
        'is_required': False,
        'is_sensitive': True,
        'options': [],
        'title': 'DeepSeek API Keys (Multi)',
        'ui_control': 'password',
        'validation': {'delimiter': ',', 'multi_value': True}},
    "GEMINI_API_KEY": {       'category': 'ai_model',
        'data_type': 'string',
        'default_value': None,
        'description': 'Single API key for Gemini service (from https://aistudio.google.com).',
        'display_order': 10,
        'docs': [       {       'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/LLM_CONFIG_GUIDE.md',
                                'label': 'LLM 配置指南'},
                        {       'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/llm-providers.md',
                                'label': 'LLM 服务商配置速查'}],
        'examples': ['GEMINI_API_KEY=your_gemini_api_key', 'LITELLM_MODEL=gemini/gemini-3.1-pro-preview'],
        'help_key': 'settings.ai_model.provider_keys',
        'is_editable': True,
        'is_required': False,
        'is_sensitive': True,
        'options': [],
        'title': 'Gemini API Key',
        'ui_control': 'password',
        'validation': {},
        'warning_codes': ['secret_value']},
    "GEMINI_API_KEYS": {       'category': 'ai_model',
        'data_type': 'string',
        'default_value': None,
        'description': 'Comma-separated Gemini API keys for load balancing. Takes priority over GEMINI_API_KEY.',
        'display_order': 11,
        'is_editable': True,
        'is_required': False,
        'is_sensitive': True,
        'options': [],
        'title': 'Gemini API Keys (Multi)',
        'ui_control': 'password',
        'validation': {'delimiter': ',', 'multi_value': True}},
    "GEMINI_MODEL": {       'category': 'ai_model',
        'data_type': 'string',
        'default_value': 'gemini-3.1-pro-preview',
        'description': 'Gemini model name.',
        'display_order': 20,
        'is_editable': True,
        'is_required': False,
        'is_sensitive': False,
        'options': [],
        'title': 'Gemini Model',
        'ui_control': 'text',
        'validation': {}},
    "GEMINI_MODEL_FALLBACK": {       'category': 'ai_model',
        'data_type': 'string',
        'default_value': 'gemini-3-flash-preview',
        'description': 'Fallback Gemini model name (used when LITELLM_FALLBACK_MODELS is not set and primary is '
                       'Gemini).',
        'display_order': 21,
        'is_editable': True,
        'is_required': False,
        'is_sensitive': False,
        'options': [],
        'title': 'Gemini Fallback Model',
        'ui_control': 'text',
        'validation': {}},
    "GEMINI_TEMPERATURE": {       'category': 'ai_model',
        'data_type': 'number',
        'default_value': '0.7',
        'description': 'Temperature in range [0.0, 2.0].',
        'display_order': 30,
        'is_editable': True,
        'is_required': False,
        'is_sensitive': False,
        'options': [],
        'title': 'Gemini Temperature',
        'ui_control': 'number',
        'validation': {'max': 2.0, 'min': 0.0}},
    "OPENAI_API_KEY": {       'category': 'ai_model',
        'data_type': 'string',
        'default_value': None,
        'description': 'API key for OpenAI-compatible service.',
        'display_order': 40,
        'docs': [       {       'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/LLM_CONFIG_GUIDE.md',
                                'label': 'LLM 配置指南'},
                        {       'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/llm-providers.md',
                                'label': 'LLM 服务商配置速查'}],
        'examples': [       'OPENAI_API_KEY=sk-xxxx',
                            'OPENAI_BASE_URL=https://api.example.com/v1',
                            'LITELLM_MODEL=openai/gpt-5.5'],
        'help_key': 'settings.ai_model.provider_keys',
        'is_editable': True,
        'is_required': False,
        'is_sensitive': True,
        'options': [],
        'title': 'OpenAI API Key',
        'ui_control': 'password',
        'validation': {},
        'warning_codes': ['secret_value']},
    "OPENAI_API_KEYS": {       'category': 'ai_model',
        'data_type': 'string',
        'default_value': None,
        'description': 'Comma-separated OpenAI-compatible API keys for load balancing. Takes priority over '
                       'AIHUBMIX_KEY and OPENAI_API_KEY.',
        'display_order': 41,
        'is_editable': True,
        'is_required': False,
        'is_sensitive': True,
        'options': [],
        'title': 'OpenAI API Keys (Multi)',
        'ui_control': 'password',
        'validation': {'delimiter': ',', 'multi_value': True}},
    "OPENAI_BASE_URL": {       'category': 'ai_model',
        'data_type': 'string',
        'default_value': None,
        'description': 'Base URL for OpenAI-compatible endpoint.',
        'display_order': 50,
        'docs': [       {       'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/LLM_CONFIG_GUIDE.md',
                                'label': 'LLM 配置指南'},
                        {       'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/llm-providers.md',
                                'label': 'LLM 服务商配置速查'}],
        'examples': ['OPENAI_BASE_URL=https://api.openai.com/v1', 'OPENAI_BASE_URL=https://api.example.com/v1'],
        'help_key': 'settings.ai_model.OPENAI_BASE_URL',
        'is_editable': True,
        'is_required': False,
        'is_sensitive': False,
        'options': [],
        'title': 'OpenAI Base URL',
        'ui_control': 'text',
        'validation': {},
        'warning_codes': ['base_url_must_match_provider']},
    "OPENAI_MODEL": {       'category': 'ai_model',
        'data_type': 'string',
        'default_value': 'gpt-5.5',
        'description': 'Model name for OpenAI-compatible endpoint.',
        'display_order': 60,
        'is_editable': True,
        'is_required': False,
        'is_sensitive': False,
        'options': [],
        'title': 'OpenAI Model',
        'ui_control': 'text',
        'validation': {}},
    "OPENAI_VISION_MODEL": {       'category': 'ai_model',
        'data_type': 'string',
        'default_value': None,
        'description': 'Model for image extraction (some APIs e.g. DeepSeek lack vision). Leave empty to use '
                       'OPENAI_MODEL.',
        'display_order': 61,
        'is_editable': True,
        'is_required': False,
        'is_sensitive': False,
        'options': [],
        'title': 'OpenAI Vision Model',
        'ui_control': 'text',
        'validation': {}},
    "OPENAI_TEMPERATURE": {       'category': 'ai_model',
        'data_type': 'number',
        'default_value': '0.7',
        'description': 'Temperature for OpenAI-compatible models in range [0.0, 2.0].',
        'display_order': 62,
        'is_editable': True,
        'is_required': False,
        'is_sensitive': False,
        'options': [],
        'title': 'OpenAI Temperature',
        'ui_control': 'number',
        'validation': {'max': 2.0, 'min': 0.0}},
    "AGNES_API_KEY": {       'category': 'ai_model',
        'data_type': 'string',
        'default_value': None,
        'description': 'API key for Agnes AI service (OpenAI-compatible). When set, auto-falls back to OPENAI_API_KEY '
                       'if OPENAI_API_KEY is empty.',
        'display_order': 63,
        'docs': [       {       'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/LLM_CONFIG_GUIDE.md',
                                'label': 'LLM 配置指南'},
                        {       'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/llm-providers.md',
                                'label': 'LLM 服务商配置速查'}],
        'examples': [       'AGNES_API_KEY=sk-xxxx',
                            'AGNES_API_BASE=https://api.agnes-ai.com/v1',
                            'LITELLM_MODEL=openai/deepseek-chat'],
        'help_key': 'settings.ai_model.provider_keys',
        'is_editable': True,
        'is_required': False,
        'is_sensitive': True,
        'options': [],
        'title': 'Agnes API Key',
        'ui_control': 'password',
        'validation': {},
        'warning_codes': ['secret_value']},
    "AGNES_API_BASE": {       'category': 'ai_model',
        'data_type': 'string',
        'default_value': 'https://api.agnes-ai.com/v1',
        'description': 'Base URL for Agnes API endpoint (OpenAI-compatible). Defaults to https://api.agnes-ai.com/v1.',
        'display_order': 64,
        'docs': [       {       'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/LLM_CONFIG_GUIDE.md',
                                'label': 'LLM 配置指南'},
                        {       'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/llm-providers.md',
                                'label': 'LLM 服务商配置速查'}],
        'examples': ['AGNES_API_BASE=https://api.agnes-ai.com/v1', 'LITELLM_MODEL=openai/deepseek-chat'],
        'help_key': 'settings.ai_model.AGNES_API_BASE',
        'is_editable': True,
        'is_required': False,
        'is_sensitive': False,
        'options': [],
        'title': 'Agnes API Base URL',
        'ui_control': 'text',
        'validation': {},
        'warning_codes': []},
    "ANTHROPIC_API_KEY": {       'category': 'ai_model',
        'data_type': 'string',
        'default_value': None,
        'description': 'Anthropic Claude API key (from https://console.anthropic.com).',
        'display_order': 35,
        'docs': [       {       'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/LLM_CONFIG_GUIDE.md',
                                'label': 'LLM 配置指南'},
                        {       'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/llm-providers.md',
                                'label': 'LLM 服务商配置速查'}],
        'examples': ['ANTHROPIC_API_KEY=sk-ant-xxxx', 'LITELLM_MODEL=anthropic/claude-sonnet-4-6'],
        'help_key': 'settings.ai_model.provider_keys',
        'is_editable': True,
        'is_required': False,
        'is_sensitive': True,
        'options': [],
        'title': 'Anthropic API Key',
        'ui_control': 'password',
        'validation': {},
        'warning_codes': ['secret_value']},
    "ANTHROPIC_API_KEYS": {       'category': 'ai_model',
        'data_type': 'string',
        'default_value': None,
        'description': 'Comma-separated Anthropic API keys for load balancing. Takes priority over ANTHROPIC_API_KEY.',
        'display_order': 35,
        'is_editable': True,
        'is_required': False,
        'is_sensitive': True,
        'options': [],
        'title': 'Anthropic API Keys (Multi)',
        'ui_control': 'password',
        'validation': {'delimiter': ',', 'multi_value': True}},
    "ANTHROPIC_MODEL": {       'category': 'ai_model',
        'data_type': 'string',
        'default_value': 'claude-sonnet-4-6',
        'description': 'Claude 模型名称（如 claude-sonnet-4-6）。',
        'display_order': 36,
        'is_editable': True,
        'is_required': False,
        'is_sensitive': False,
        'options': [],
        'title': 'Anthropic Model',
        'ui_control': 'text',
        'validation': {}},
    "ANTHROPIC_TEMPERATURE": {       'category': 'ai_model',
        'data_type': 'number',
        'default_value': '0.7',
        'description': '温度参数，范围 [0.0, 1.0]。',
        'display_order': 37,
        'is_editable': True,
        'is_required': False,
        'is_sensitive': False,
        'options': [],
        'title': 'Anthropic Temperature',
        'ui_control': 'number',
        'validation': {'max': 1.0, 'min': 0.0}},
    "ANTHROPIC_MAX_TOKENS": {       'category': 'ai_model',
        'data_type': 'number',
        'default_value': '8192',
        'description': 'Anthropic API 响应最大 token 数（默认 8192）。',
        'display_order': 38,
        'is_editable': True,
        'is_required': False,
        'is_sensitive': False,
        'options': [],
        'title': 'Anthropic Max Tokens',
        'ui_control': 'number',
        'validation': {'max': 8192, 'min': 256}}
}
