"""
字段定义 - backtest 分类
从 config_registry.py 按 category 拆分
"""

FIELD_DEFINITIONS: dict = {
    "BACKTEST_ENABLED": {       'category': 'backtest',
        'data_type': 'boolean',
        'default_value': 'true',
        'description': 'Whether backtest is enabled.',
        'display_order': 10,
        'docs': [       {       'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/full-guide.md#回测功能',
                                'label': '完整指南：回测配置'}],
        'examples': ['BACKTEST_ENABLED=true', 'BACKTEST_ENABLED=false'],
        'help_key': 'settings.backtest.BACKTEST_ENABLED',
        'is_editable': True,
        'is_required': False,
        'is_sensitive': False,
        'options': [],
        'title': 'Backtest Enabled',
        'ui_control': 'switch',
        'validation': {},
        'warning_codes': []},
    "BACKTEST_EVAL_WINDOW_DAYS": {       'category': 'backtest',
        'data_type': 'integer',
        'default_value': '10',
        'description': 'Backtest evaluation window in trading days.',
        'display_order': 20,
        'docs': [       {       'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/full-guide.md#回测功能',
                                'label': '完整指南：回测配置'}],
        'examples': ['BACKTEST_EVAL_WINDOW_DAYS=10', 'BACKTEST_MIN_AGE_DAYS=14', 'BACKTEST_NEUTRAL_BAND_PCT=2.0'],
        'help_key': 'settings.backtest.eval_params',
        'is_editable': True,
        'is_required': False,
        'is_sensitive': False,
        'options': [],
        'title': 'Backtest Eval Window Days',
        'ui_control': 'number',
        'validation': {'max': 365, 'min': 1},
        'warning_codes': []},
    "BACKTEST_MIN_AGE_DAYS": {       'category': 'backtest',
        'data_type': 'integer',
        'default_value': '14',
        'description': 'Only evaluate analysis records older than this threshold.',
        'display_order': 30,
        'docs': [       {       'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/full-guide.md#回测功能',
                                'label': '完整指南：回测配置'}],
        'examples': ['BACKTEST_MIN_AGE_DAYS=14', 'BACKTEST_EVAL_WINDOW_DAYS=10'],
        'help_key': 'settings.backtest.eval_params',
        'is_editable': True,
        'is_required': False,
        'is_sensitive': False,
        'options': [],
        'title': 'Backtest Min Age Days',
        'ui_control': 'number',
        'validation': {'max': 3650, 'min': 0},
        'warning_codes': []},
    "BACKTEST_ENGINE_VERSION": {       'category': 'backtest',
        'data_type': 'string',
        'default_value': 'v1',
        'description': 'Backtest engine version label.',
        'display_order': 40,
        'docs': [       {       'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/full-guide.md#回测功能',
                                'label': '完整指南：回测配置'}],
        'examples': ['BACKTEST_ENGINE_VERSION=v1'],
        'help_key': 'settings.backtest.BACKTEST_ENGINE_VERSION',
        'is_editable': True,
        'is_required': False,
        'is_sensitive': False,
        'options': [],
        'title': 'Backtest Engine Version',
        'ui_control': 'text',
        'validation': {},
        'warning_codes': []},
    "BACKTEST_NEUTRAL_BAND_PCT": {       'category': 'backtest',
        'data_type': 'number',
        'default_value': '2.0',
        'description': 'Neutral return band percentage for outcome labeling.',
        'display_order': 50,
        'docs': [       {       'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/full-guide.md#回测功能',
                                'label': '完整指南：回测配置'}],
        'examples': ['BACKTEST_NEUTRAL_BAND_PCT=2.0', 'BACKTEST_EVAL_WINDOW_DAYS=10'],
        'help_key': 'settings.backtest.eval_params',
        'is_editable': True,
        'is_required': False,
        'is_sensitive': False,
        'options': [],
        'title': 'Backtest Neutral Band Pct',
        'ui_control': 'number',
        'validation': {'max': 100.0, 'min': 0.0},
        'warning_codes': []},
    "EXECUTION_ENABLED": {       'category': 'backtest',
        'data_type': 'boolean',
        'default_value': 'false',
        'description': 'Whether phase 4 atomic execution planning is enabled.',
        'display_order': 45,
        'docs': [       {       'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/full-guide.md#回测功能',
                                'label': '完整指南：回测配置'}],
        'examples': ['EXECUTION_ENABLED=false', 'EXECUTION_ENABLED=true'],
        'help_key': 'settings.backtest.EXECUTION_ENABLED',
        'is_editable': True,
        'is_required': False,
        'is_sensitive': False,
        'options': [],
        'title': 'Execution Enabled',
        'ui_control': 'switch',
        'validation': {},
        'warning_codes': []}
}
