"""
字段定义 - data_source 分类
从 config_registry.py 按 category 拆分
"""

FIELD_DEFINITIONS: dict = {
    "TUSHARE_TOKEN": {       'category': 'data_source',
        'data_type': 'string',
        'default_value': None,
        'description': 'Token for Tushare Pro API.',
        'display_order': 10,
        'docs': [       {       'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/TUSHARE_STOCK_LIST_GUIDE.md',
                                'label': 'Tushare 股票列表指南'},
                        {       'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/full-guide.md#环境变量完整列表',
                                'label': '完整指南：环境变量完整列表'}],
        'examples': ['TUSHARE_TOKEN=your_tushare_token'],
        'help_key': 'settings.data_source.TUSHARE_TOKEN',
        'is_editable': True,
        'is_required': False,
        'is_sensitive': True,
        'options': [],
        'title': 'Tushare Token',
        'ui_control': 'password',
        'validation': {},
        'warning_codes': ['secret_value']},
    "TICKFLOW_API_KEY": {       'category': 'data_source',
        'data_type': 'string',
        'default_value': None,
        'description': 'API key for TickFlow market review enhancement (A-share indices, plus market stats when '
                       'universe queries are enabled).',
        'display_order': 15,
        'is_editable': True,
        'is_required': False,
        'is_sensitive': True,
        'options': [],
        'title': 'TickFlow API Key',
        'ui_control': 'password',
        'validation': {}},
    "STOCK_INDEX_REMOTE_UPDATE_ENABLED": {       'category': 'data_source',
        'data_type': 'boolean',
        'default_value': 'true',
        'description': 'Automatically refresh the local stock autocomplete index from the built-in GitHub main source.',
        'display_order': 16,
        'docs': [       {       'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/TUSHARE_STOCK_LIST_GUIDE.md',
                                'label': 'Tushare 股票列表指南'}],
        'examples': ['STOCK_INDEX_REMOTE_UPDATE_ENABLED=true', 'STOCK_INDEX_REMOTE_UPDATE_ENABLED=false'],
        'help_key': 'settings.data_source.stock_index_remote',
        'is_editable': True,
        'is_required': False,
        'is_sensitive': False,
        'options': [],
        'title': 'Remote Stock Index Updates',
        'ui_control': 'switch',
        'validation': {},
        'warning_codes': []},
    "ALPHASIFT_ENABLED": {       'category': 'data_source',
        'data_type': 'boolean',
        'default_value': 'true',
        'description': 'Enable the optional AlphaSift stock screening tab. Enabled by default.',
        'display_order': 17,
        'docs': [       {       'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/alphasift-integration.md',
                                'label': 'AlphaSift 集成说明'}],
        'examples': ['ALPHASIFT_ENABLED=true', 'ALPHASIFT_ENABLED=false'],
        'help_key': 'settings.data_source.ALPHASIFT_ENABLED',
        'is_editable': True,
        'is_required': False,
        'is_sensitive': False,
        'options': [],
        'title': 'AlphaSift Screening',
        'ui_control': 'switch',
        'validation': {}},
    "ALPHASIFT_INSTALL_SPEC": {       'category': 'data_source',
        'data_type': 'string',
        'default_value': 'git+https://github.com/ZhuLinsen/alphasift.git@b2ca66dd47001b9a09890cfe21c2b18c7219ccf5',
        'description': 'Pinned AlphaSift pip install spec used by source deployments and desktop packaging.',
        'display_order': 18,
        'docs': [       {       'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/alphasift-integration.md',
                                'label': 'AlphaSift 集成说明'}],
        'examples': [       'ALPHASIFT_INSTALL_SPEC=git+https://github.com/ZhuLinsen/alphasift.git@b2ca66dd47001b9a09890cfe21c2b18c7219ccf5'],
        'help_key': 'settings.data_source.ALPHASIFT_INSTALL_SPEC',
        'is_editable': True,
        'is_required': False,
        'is_sensitive': True,
        'options': [],
        'title': 'AlphaSift Install Spec',
        'ui_control': 'password',
        'validation': {}},
    "FACTOR_PIPELINE_ENABLED": {       'category': 'data_source',
        'data_type': 'boolean',
        'default_value': 'false',
        'description': 'Enable the experimental multi-factor screening pipeline.',
        'display_order': 19,
        'docs': [       {       'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/roadmap.md',
                                'label': 'Phase 2 路线图'}],
        'examples': ['FACTOR_PIPELINE_ENABLED=false', 'FACTOR_PIPELINE_ENABLED=true'],
        'help_key': 'settings.data_source.FACTOR_PIPELINE_ENABLED',
        'is_editable': True,
        'is_required': False,
        'is_sensitive': False,
        'options': [],
        'title': 'Factor Pipeline',
        'ui_control': 'switch',
        'validation': {}},
    "FACTOR_PIPELINE_TRAIN_DAYS": {       'category': 'data_source',
        'data_type': 'number',
        'default_value': '730',
        'description': 'Rolling training window length in days for the factor pipeline.',
        'display_order': 20,
        'examples': ['FACTOR_PIPELINE_TRAIN_DAYS=730'],
        'help_key': 'settings.data_source.FACTOR_PIPELINE_TRAIN_DAYS',
        'is_editable': True,
        'is_required': False,
        'is_sensitive': False,
        'options': [],
        'title': 'Factor Pipeline Train Days',
        'ui_control': 'number',
        'validation': {'max': 3650, 'min': 90}},
    "FACTOR_PIPELINE_VALID_DAYS": {       'category': 'data_source',
        'data_type': 'number',
        'default_value': '90',
        'description': 'Validation window length in days for the factor pipeline.',
        'display_order': 21,
        'examples': ['FACTOR_PIPELINE_VALID_DAYS=90'],
        'help_key': 'settings.data_source.FACTOR_PIPELINE_VALID_DAYS',
        'is_editable': True,
        'is_required': False,
        'is_sensitive': False,
        'options': [],
        'title': 'Factor Pipeline Valid Days',
        'ui_control': 'number',
        'validation': {'max': 730, 'min': 30}},
    "FACTOR_PIPELINE_TEST_DAYS": {       'category': 'data_source',
        'data_type': 'number',
        'default_value': '90',
        'description': 'Test window length in days for the factor pipeline.',
        'display_order': 22,
        'examples': ['FACTOR_PIPELINE_TEST_DAYS=90'],
        'help_key': 'settings.data_source.FACTOR_PIPELINE_TEST_DAYS',
        'is_editable': True,
        'is_required': False,
        'is_sensitive': False,
        'options': [],
        'title': 'Factor Pipeline Test Days',
        'ui_control': 'number',
        'validation': {'max': 730, 'min': 30}},
    "FACTOR_PIPELINE_SHAP_SAMPLE_SIZE": {       'category': 'data_source',
        'data_type': 'number',
        'default_value': '128',
        'description': 'Maximum sample size used when computing SHAP explanations.',
        'display_order': 23,
        'examples': ['FACTOR_PIPELINE_SHAP_SAMPLE_SIZE=128'],
        'help_key': 'settings.data_source.FACTOR_PIPELINE_SHAP_SAMPLE_SIZE',
        'is_editable': True,
        'is_required': False,
        'is_sensitive': False,
        'options': [],
        'title': 'Factor Pipeline SHAP Sample Size',
        'ui_control': 'number',
        'validation': {'max': 2048, 'min': 1}},
    "FACTOR_PIPELINE_INSTRUMENTS": {       'category': 'data_source',
        'data_type': 'string',
        'default_value': 'csi300',
        'description': 'Qlib instrument universe for the factor pipeline.',
        'display_order': 24,
        'examples': ['FACTOR_PIPELINE_INSTRUMENTS=csi300'],
        'help_key': 'settings.data_source.FACTOR_PIPELINE_INSTRUMENTS',
        'is_editable': True,
        'is_required': False,
        'is_sensitive': False,
        'options': [],
        'title': 'Factor Pipeline Instruments',
        'ui_control': 'text',
        'validation': {}},
    "FACTOR_QLIB_PROVIDER_URI": {       'category': 'data_source',
        'data_type': 'string',
        'default_value': '',
        'description': 'Provider URI for the real Qlib backend.',
        'display_order': 25,
        'examples': ['FACTOR_QLIB_PROVIDER_URI=/path/to/qlib/provider'],
        'help_key': 'settings.data_source.FACTOR_QLIB_PROVIDER_URI',
        'is_editable': True,
        'is_required': False,
        'is_sensitive': True,
        'options': [],
        'title': 'Qlib Provider URI',
        'ui_control': 'password',
        'validation': {}},
    "FACTOR_QLIB_REGION": {       'category': 'data_source',
        'data_type': 'string',
        'default_value': 'cn',
        'description': 'Qlib market region for the real factor backend.',
        'display_order': 26,
        'examples': ['FACTOR_QLIB_REGION=cn', 'FACTOR_QLIB_REGION=us'],
        'help_key': 'settings.data_source.FACTOR_QLIB_REGION',
        'is_editable': True,
        'is_required': False,
        'is_sensitive': False,
        'options': [],
        'title': 'Qlib Region',
        'ui_control': 'text',
        'validation': {}},
    "REALTIME_SOURCE_PRIORITY": {       'category': 'data_source',
        'data_type': 'string',
        'default_value': 'tencent,akshare_sina,efinance,akshare_em',
        'description': 'Comma-separated priority for realtime quote providers.',
        'display_order': 20,
        'docs': [       {       'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/full-guide.md#数据源配置',
                                'label': '完整指南：数据源配置'}],
        'examples': ['REALTIME_SOURCE_PRIORITY=tencent,akshare_sina,efinance,akshare_em'],
        'help_key': 'settings.data_source.REALTIME_SOURCE_PRIORITY',
        'is_editable': True,
        'is_required': False,
        'is_sensitive': False,
        'options': [],
        'title': 'Realtime Source Priority',
        'ui_control': 'text',
        'validation': {},
        'warning_codes': ['provider_priority_order']},
    "ENABLE_REALTIME_TECHNICAL_INDICATORS": {       'category': 'data_source',
        'data_type': 'boolean',
        'default_value': 'true',
        'description': 'Use intraday realtime price for MA5/MA10/MA20 and trend analysis (Issue #234). Disable to use '
                       'yesterday close.',
        'display_order': 21,
        'docs': [       {       'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/full-guide.md#数据源配置',
                                'label': '完整指南：数据源配置'}],
        'examples': ['ENABLE_REALTIME_TECHNICAL_INDICATORS=true', 'ENABLE_REALTIME_TECHNICAL_INDICATORS=false'],
        'help_key': 'settings.data_source.realtime_quotes',
        'is_editable': True,
        'is_required': False,
        'is_sensitive': False,
        'options': [],
        'title': 'Realtime Technical Indicators',
        'ui_control': 'switch',
        'validation': {},
        'warning_codes': []},
    "ANSPIRE_API_KEYS": {       'category': 'data_source',
        'data_type': 'string',
        'default_value': None,
        'description': 'Comma-separated Anspire Open API keys. Used by Anspire Search and, by default, the Anspire '
                       'OpenAI-compatible LLM gateway.',
        'display_order': 22,
        'docs': [       {       'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/full-guide.md#搜索服务配置',
                                'label': '完整指南：搜索服务配置'}],
        'examples': ['ANSPIRE_API_KEYS=key1,key2'],
        'help_key': 'settings.data_source.search_api_keys',
        'is_editable': True,
        'is_required': False,
        'is_sensitive': True,
        'options': [],
        'title': 'Anspire API Keys',
        'ui_control': 'password',
        'validation': {'delimiter': ',', 'multi_value': True},
        'warning_codes': ['secret_value', 'comma_separated_keys']},
    "TAVILY_API_KEYS": {       'category': 'data_source',
        'data_type': 'string',
        'default_value': None,
        'description': 'Comma-separated Tavily API keys.',
        'display_order': 30,
        'docs': [       {       'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/full-guide.md#搜索服务配置',
                                'label': '完整指南：搜索服务配置'}],
        'examples': ['TAVILY_API_KEYS=tvly-xxxx', 'TAVILY_API_KEYS=tvly-key-1,tvly-key-2'],
        'help_key': 'settings.data_source.search_api_keys',
        'is_editable': True,
        'is_required': False,
        'is_sensitive': True,
        'options': [],
        'title': 'Tavily API Keys',
        'ui_control': 'password',
        'validation': {'delimiter': ',', 'multi_value': True},
        'warning_codes': ['secret_value', 'comma_separated_keys']},
    "SERPAPI_API_KEYS": {       'category': 'data_source',
        'data_type': 'string',
        'default_value': None,
        'description': 'Comma-separated SerpAPI keys.',
        'display_order': 40,
        'is_editable': True,
        'is_required': False,
        'is_sensitive': True,
        'options': [],
        'title': 'SerpAPI Keys',
        'ui_control': 'password',
        'validation': {'delimiter': ',', 'multi_value': True}},
    "BRAVE_API_KEYS": {       'category': 'data_source',
        'data_type': 'string',
        'default_value': None,
        'description': 'Comma-separated Brave Search API keys.',
        'display_order': 50,
        'is_editable': True,
        'is_required': False,
        'is_sensitive': True,
        'options': [],
        'title': 'Brave API Keys',
        'ui_control': 'password',
        'validation': {'delimiter': ',', 'multi_value': True}},
    "BOCHA_API_KEYS": {       'category': 'data_source',
        'data_type': 'string',
        'default_value': None,
        'description': 'Comma-separated Bocha Search API keys.',
        'display_order': 51,
        'is_editable': True,
        'is_required': False,
        'is_sensitive': True,
        'options': [],
        'title': 'Bocha API Keys',
        'ui_control': 'password',
        'validation': {'delimiter': ',', 'multi_value': True}},
    "MINIMAX_API_KEYS": {       'category': 'data_source',
        'data_type': 'string',
        'default_value': None,
        'description': 'MiniMax API key (search priority: Bocha > Tavily > Brave > SerpAPI > MiniMax > SearXNG).',
        'display_order': 53,
        'is_editable': True,
        'is_required': False,
        'is_sensitive': True,
        'options': [],
        'title': 'MiniMax API Key',
        'ui_control': 'password',
        'validation': {'delimiter': ',', 'multi_value': True}},
    "SEARXNG_BASE_URLS": {       'category': 'data_source',
        'data_type': 'string',
        'default_value': None,
        'description': 'Comma-separated SearXNG instance URLs (self-hosted, no quota). Enable format: json in '
                       'settings.yml.',
        'display_order': 52,
        'docs': [       {       'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/full-guide.md#搜索服务配置',
                                'label': '完整指南：搜索服务配置'}],
        'examples': ['SEARXNG_BASE_URLS=https://search.example.com', 'SEARXNG_PUBLIC_INSTANCES_ENABLED=false'],
        'help_key': 'settings.data_source.SEARXNG_BASE_URLS',
        'is_editable': True,
        'is_required': False,
        'is_sensitive': False,
        'options': [],
        'title': 'SearXNG Base URLs',
        'ui_control': 'text',
        'validation': {'allowed_schemes': ['http', 'https'], 'delimiter': ',', 'item_type': 'url', 'multi_value': True},
        'warning_codes': ['requires_json_format']},
    "SEARXNG_PUBLIC_INSTANCES_ENABLED": {       'category': 'data_source',
        'data_type': 'boolean',
        'default_value': 'true',
        'description': 'Auto-discover public SearXNG instances from searx.space when SEARXNG_BASE_URLS is empty. '
                       'Default: true; set false to disable.',
        'display_order': 53,
        'is_editable': True,
        'is_required': False,
        'is_sensitive': False,
        'options': [],
        'title': 'SearXNG Public Instances',
        'ui_control': 'switch',
        'validation': {}},
    "ENABLE_REALTIME_QUOTE": {       'category': 'data_source',
        'data_type': 'boolean',
        'default_value': 'true',
        'description': 'Enable realtime market quotes. Disable to only use historical close prices.',
        'display_order': 22,
        'docs': [       {       'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/full-guide.md#数据源配置',
                                'label': '完整指南：数据源配置'}],
        'examples': ['ENABLE_REALTIME_QUOTE=true', 'ENABLE_REALTIME_QUOTE=false'],
        'help_key': 'settings.data_source.realtime_quotes',
        'is_editable': True,
        'is_required': False,
        'is_sensitive': False,
        'options': [],
        'title': 'Enable Realtime Quote',
        'ui_control': 'switch',
        'validation': {},
        'warning_codes': []},
    "ENABLE_CHIP_DISTRIBUTION": {       'category': 'data_source',
        'data_type': 'boolean',
        'default_value': 'true',
        'description': 'Enable chip distribution analysis. May be unstable; recommended to disable on cloud '
                       'deployments.',
        'display_order': 23,
        'docs': [       {       'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/full-guide.md#数据源配置',
                                'label': '完整指南：数据源配置'}],
        'examples': ['ENABLE_CHIP_DISTRIBUTION=true', 'ENABLE_CHIP_DISTRIBUTION=false'],
        'help_key': 'settings.data_source.ENABLE_CHIP_DISTRIBUTION',
        'is_editable': True,
        'is_required': False,
        'is_sensitive': False,
        'options': [],
        'title': 'Enable Chip Distribution',
        'ui_control': 'switch',
        'validation': {},
        'warning_codes': ['cloud_deployments_may_disable']},
    "NEWS_MAX_AGE_DAYS": {       'category': 'data_source',
        'data_type': 'integer',
        'default_value': '3',
        'description': 'Maximum age of news in days. Older articles are excluded from analysis context.',
        'display_order': 60,
        'docs': [       {       'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/full-guide.md#环境变量完整列表',
                                'label': '完整指南：环境变量完整列表'}],
        'examples': ['NEWS_MAX_AGE_DAYS=3', 'NEWS_STRATEGY_PROFILE=short'],
        'help_key': 'settings.data_source.news_window',
        'is_editable': True,
        'is_required': False,
        'is_sensitive': False,
        'options': [],
        'title': 'News Max Age (Days)',
        'ui_control': 'number',
        'validation': {'max': 30, 'min': 1},
        'warning_codes': []},
    "NEWS_STRATEGY_PROFILE": {       'category': 'data_source',
        'data_type': 'string',
        'default_value': 'short',
        'description': 'News window profile: ultra_short(1d), short(3d), medium(7d), long(30d). Effective window = '
                       'min(profile, NEWS_MAX_AGE_DAYS).',
        'display_order': 61,
        'docs': [       {       'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/full-guide.md#环境变量完整列表',
                                'label': '完整指南：环境变量完整列表'}],
        'examples': ['NEWS_STRATEGY_PROFILE=short', 'NEWS_MAX_AGE_DAYS=3'],
        'help_key': 'settings.data_source.news_window',
        'is_editable': True,
        'is_required': False,
        'is_sensitive': False,
        'options': ['ultra_short', 'short', 'medium', 'long'],
        'title': 'News Strategy Profile',
        'ui_control': 'select',
        'validation': {'enum': ['ultra_short', 'short', 'medium', 'long']},
        'warning_codes': []},
    "BIAS_THRESHOLD": {       'category': 'data_source',
        'data_type': 'number',
        'default_value': '5.0',
        'description': "Deviation threshold from MA5 (%). Exceeding this triggers 'do not chase' warning. Strong trend "
                       'stocks auto-widen to 1.5x.',
        'display_order': 62,
        'is_editable': True,
        'is_required': False,
        'is_sensitive': False,
        'options': [],
        'title': 'Bias Threshold (%)',
        'ui_control': 'number',
        'validation': {'max': 50.0, 'min': 0.0}},
    "PYTDX_HOST": {       'category': 'data_source',
        'data_type': 'string',
        'default_value': None,
        'description': 'Tongdaxin data server IP. Used with PYTDX_PORT. Overrides built-in defaults.',
        'display_order': 55,
        'is_editable': True,
        'is_required': False,
        'is_sensitive': False,
        'options': [],
        'title': 'Pytdx Host',
        'ui_control': 'text',
        'validation': {}},
    "PYTDX_PORT": {       'category': 'data_source',
        'data_type': 'string',
        'default_value': None,
        'description': 'Tongdaxin data server port (e.g. 7709). Used with PYTDX_HOST.',
        'display_order': 56,
        'is_editable': True,
        'is_required': False,
        'is_sensitive': False,
        'options': [],
        'title': 'Pytdx Port',
        'ui_control': 'text',
        'validation': {}},
    "PYTDX_SERVERS": {       'category': 'data_source',
        'data_type': 'string',
        'default_value': None,
        'description': 'Comma-separated ip:port (e.g. 192.168.1.1:7709,10.0.0.1:7709). Overrides '
                       'PYTDX_HOST+PYTDX_PORT.',
        'display_order': 57,
        'is_editable': True,
        'is_required': False,
        'is_sensitive': False,
        'options': [],
        'title': 'Pytdx Servers',
        'ui_control': 'text',
        'validation': {}}
}
