"""字段帮助元数据"""

_FIELD_HELP_METADATA = {   'AGNES_API_BASE': {   'docs': [   {   'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/LLM_CONFIG_GUIDE.md',
                                          'label': 'LLM 配置指南'},
                                      {   'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/llm-providers.md',
                                          'label': 'LLM 服务商配置速查'}],
                          'examples': [   'AGNES_API_BASE=https://api.agnes-ai.com/v1',
                                          'LITELLM_MODEL=openai/deepseek-chat'],
                          'help_key': 'settings.ai_model.AGNES_API_BASE',
                          'warning_codes': []},
    'AGNES_API_KEY': {   'docs': [   {   'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/LLM_CONFIG_GUIDE.md',
                                         'label': 'LLM 配置指南'},
                                     {   'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/llm-providers.md',
                                         'label': 'LLM 服务商配置速查'}],
                         'examples': [   'AGNES_API_KEY=sk-xxxx',
                                         'AGNES_API_BASE=https://api.agnes-ai.com/v1',
                                         'LITELLM_MODEL=openai/deepseek-chat'],
                         'help_key': 'settings.ai_model.provider_keys',
                         'warning_codes': ['secret_value']},
    'ANSPIRE_LLM_BASE_URL': {   'docs': [   {   'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/LLM_CONFIG_GUIDE.md',
                                                'label': 'LLM 配置指南'},
                                            {   'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/llm-providers.md',
                                                'label': 'LLM 服务商配置速查'}],
                                'examples': [   'ANSPIRE_LLM_BASE_URL=https://open-gateway.anspire.cn/v6',
                                                'ANSPIRE_LLM_BASE_URL=https://open-gateway.anspire.ai/v6'],
                                'help_key': 'settings.ai_model.anspire_llm',
                                'warning_codes': ['base_url_must_match_provider']},
    'ANSPIRE_LLM_ENABLED': {   'docs': [   {   'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/LLM_CONFIG_GUIDE.md',
                                               'label': 'LLM 配置指南'},
                                           {   'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/llm-providers.md',
                                               'label': 'LLM 服务商配置速查'}],
                               'examples': ['ANSPIRE_LLM_ENABLED=true', 'ANSPIRE_API_KEYS=your_anspire_key'],
                               'help_key': 'settings.ai_model.anspire_llm',
                               'warning_codes': []},
    'ANSPIRE_LLM_MODEL': {   'docs': [   {   'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/LLM_CONFIG_GUIDE.md',
                                             'label': 'LLM 配置指南'},
                                         {   'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/llm-providers.md',
                                             'label': 'LLM 服务商配置速查'}],
                             'examples': [   'ANSPIRE_LLM_MODEL=Doubao-Seed-2.0-lite',
                                             'LITELLM_MODEL=openai/Doubao-Seed-2.0-lite'],
                             'help_key': 'settings.ai_model.anspire_llm',
                             'warning_codes': []},
    'ANTHROPIC_API_KEYS': {   'docs': [   {   'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/LLM_CONFIG_GUIDE.md',
                                              'label': 'LLM 配置指南'},
                                          {   'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/llm-providers.md',
                                              'label': 'LLM 服务商配置速查'}],
                              'examples': [   'ANTHROPIC_API_KEYS=sk-ant-xxxx,sk-ant-yyyy',
                                              'LITELLM_MODEL=anthropic/claude-sonnet-4-6'],
                              'help_key': 'settings.ai_model.provider_keys',
                              'warning_codes': ['secret_value', 'comma_separated_keys']},
    'ANTHROPIC_MAX_TOKENS': {   'docs': [   {   'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/LLM_CONFIG_GUIDE.md',
                                                'label': 'LLM 配置指南'},
                                            {   'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/llm-providers.md',
                                                'label': 'LLM 服务商配置速查'}],
                                'examples': ['ANTHROPIC_MAX_TOKENS=8192'],
                                'help_key': 'settings.ai_model.legacy_provider_params',
                                'warning_codes': ['legacy_provider_setting']},
    'ANTHROPIC_MODEL': {   'docs': [   {   'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/LLM_CONFIG_GUIDE.md',
                                           'label': 'LLM 配置指南'},
                                       {   'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/llm-providers.md',
                                           'label': 'LLM 服务商配置速查'}],
                           'examples': [   'ANTHROPIC_MODEL=claude-sonnet-4-6',
                                           'LITELLM_MODEL=anthropic/claude-sonnet-4-6'],
                           'help_key': 'settings.ai_model.legacy_provider_params',
                           'warning_codes': ['legacy_provider_setting']},
    'ANTHROPIC_TEMPERATURE': {   'docs': [   {   'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/LLM_CONFIG_GUIDE.md',
                                                 'label': 'LLM 配置指南'},
                                             {   'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/llm-providers.md',
                                                 'label': 'LLM 服务商配置速查'}],
                                 'examples': ['ANTHROPIC_TEMPERATURE=0.7', 'LLM_TEMPERATURE=0.7'],
                                 'help_key': 'settings.ai_model.legacy_provider_params',
                                 'warning_codes': ['legacy_provider_setting']},
    'ASTRBOT_TOKEN': {   'docs': [   {   'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/full-guide.md#通知渠道详细配置',
                                         'label': '完整指南：通知渠道配置'}],
                         'examples': ['ASTRBOT_TOKEN=your_astrbot_token'],
                         'help_key': 'settings.notification.chat_bots',
                         'warning_codes': ['secret_value']},
    'ASTRBOT_URL': {   'docs': [   {   'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/full-guide.md#通知渠道详细配置',
                                       'label': '完整指南：通知渠道配置'}],
                       'examples': [   'ASTRBOT_URL=https://astrbot.example.com/webhook',
                                       'ASTRBOT_TOKEN=your_astrbot_token'],
                       'help_key': 'settings.notification.chat_bots',
                       'warning_codes': ['webhook_secret_value']},
    'BIAS_THRESHOLD': {   'docs': [   {   'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/full-guide.md#数据源配置',
                                          'label': '完整指南：数据源配置'}],
                          'examples': ['BIAS_THRESHOLD=5.0', 'BIAS_THRESHOLD=8.0'],
                          'help_key': 'settings.data_source.BIAS_THRESHOLD',
                          'warning_codes': []},
    'BOCHA_API_KEYS': {   'docs': [   {   'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/full-guide.md#搜索服务配置',
                                          'label': '完整指南：搜索服务配置'}],
                          'examples': ['BOCHA_API_KEYS=bocha_key_1,bocha_key_2'],
                          'help_key': 'settings.data_source.search_api_keys',
                          'warning_codes': ['secret_value', 'comma_separated_keys']},
    'BRAVE_API_KEYS': {   'docs': [   {   'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/full-guide.md#搜索服务配置',
                                          'label': '完整指南：搜索服务配置'}],
                          'examples': ['BRAVE_API_KEYS=brave_key_1,brave_key_2'],
                          'help_key': 'settings.data_source.search_api_keys',
                          'warning_codes': ['secret_value', 'comma_separated_keys']},
    'CUSTOM_WEBHOOK_BEARER_TOKEN': {   'docs': [   {   'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/full-guide.md#自定义-webhook',
                                                       'label': '完整指南：自定义 Webhook'}],
                                       'examples': ['CUSTOM_WEBHOOK_BEARER_TOKEN=your_bearer_token'],
                                       'help_key': 'settings.notification.CUSTOM_WEBHOOK_URLS',
                                       'warning_codes': ['secret_value']},
    'CUSTOM_WEBHOOK_BODY_TEMPLATE': {   'docs': [   {   'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/full-guide.md#自定义-webhook',
                                                        'label': '完整指南：自定义 Webhook'}],
                                        'examples': [   'CUSTOM_WEBHOOK_BODY_TEMPLATE={"msg_type":"text","content":$content_json}',
                                                        'CUSTOM_WEBHOOK_BODY_TEMPLATE={"title":$title_json,"text":$content_json}'],
                                        'help_key': 'settings.notification.CUSTOM_WEBHOOK_URLS',
                                        'warning_codes': ['json_template_must_render_object']},
    'DEEPSEEK_API_KEYS': {   'docs': [   {   'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/LLM_CONFIG_GUIDE.md',
                                             'label': 'LLM 配置指南'},
                                         {   'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/llm-providers.md',
                                             'label': 'LLM 服务商配置速查'}],
                             'examples': [   'DEEPSEEK_API_KEYS=sk-xxxx,sk-yyyy',
                                             'LITELLM_MODEL=deepseek/deepseek-v4-flash'],
                             'help_key': 'settings.ai_model.provider_keys',
                             'warning_codes': ['secret_value', 'comma_separated_keys']},
    'DINGTALK_APP_KEY': {   'docs': [   {   'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/full-guide.md#通知渠道详细配置',
                                            'label': '完整指南：通知渠道配置'}],
                            'examples': [   'DINGTALK_APP_KEY=your_dingtalk_app_key',
                                            'DINGTALK_APP_SECRET=your_dingtalk_app_secret'],
                            'help_key': 'settings.notification.chat_bots',
                            'warning_codes': ['secret_value']},
    'DINGTALK_APP_SECRET': {   'docs': [   {   'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/full-guide.md#通知渠道详细配置',
                                               'label': '完整指南：通知渠道配置'}],
                               'examples': ['DINGTALK_APP_SECRET=your_dingtalk_app_secret'],
                               'help_key': 'settings.notification.chat_bots',
                               'warning_codes': ['secret_value']},
    'DISCORD_INTERACTIONS_PUBLIC_KEY': {   'docs': [   {   'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/full-guide.md#通知渠道详细配置',
                                                           'label': '完整指南：通知渠道配置'}],
                                           'examples': ['DISCORD_INTERACTIONS_PUBLIC_KEY=your_discord_public_key'],
                                           'help_key': 'settings.notification.chat_bots',
                                           'warning_codes': []},
    'DISCORD_MAIN_CHANNEL_ID': {   'docs': [   {   'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/full-guide.md#通知渠道详细配置',
                                                   'label': '完整指南：通知渠道配置'}],
                                   'examples': ['DISCORD_MAIN_CHANNEL_ID=123456789012345678'],
                                   'help_key': 'settings.notification.chat_bots',
                                   'warning_codes': []},
    'FEISHU_APP_ID': {   'docs': [   {   'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/full-guide.md#通知渠道详细配置',
                                         'label': '完整指南：通知渠道配置'}],
                         'examples': ['FEISHU_APP_ID=cli_xxxxx', 'FEISHU_APP_SECRET=your_feishu_app_secret'],
                         'help_key': 'settings.notification.FEISHU_WEBHOOK_URL',
                         'warning_codes': ['not_webhook_delivery']},
    'FEISHU_APP_SECRET': {   'docs': [   {   'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/full-guide.md#通知渠道详细配置',
                                             'label': '完整指南：通知渠道配置'}],
                             'examples': ['FEISHU_APP_SECRET=your_feishu_app_secret'],
                             'help_key': 'settings.notification.FEISHU_WEBHOOK_URL',
                             'warning_codes': ['secret_value', 'not_webhook_delivery']},
    'FEISHU_WEBHOOK_KEYWORD': {   'docs': [   {   'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/full-guide.md#通知渠道详细配置',
                                                  'label': '完整指南：通知渠道配置'}],
                                  'examples': ['FEISHU_WEBHOOK_KEYWORD=股票日报'],
                                  'help_key': 'settings.notification.FEISHU_WEBHOOK_URL',
                                  'warning_codes': []},
    'FEISHU_WEBHOOK_SECRET': {   'docs': [   {   'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/full-guide.md#通知渠道详细配置',
                                                 'label': '完整指南：通知渠道配置'},
                                             {   'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/bot/feishu-bot-config.md',
                                                 'label': '飞书机器人配置专题'}],
                                 'examples': ['FEISHU_WEBHOOK_SECRET=your_feishu_webhook_secret'],
                                 'help_key': 'settings.notification.FEISHU_WEBHOOK_URL',
                                 'warning_codes': ['secret_value']},
    'GEMINI_API_KEYS': {   'docs': [   {   'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/LLM_CONFIG_GUIDE.md',
                                           'label': 'LLM 配置指南'},
                                       {   'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/llm-providers.md',
                                           'label': 'LLM 服务商配置速查'}],
                           'examples': [   'GEMINI_API_KEYS=your_gemini_key_1,your_gemini_key_2',
                                           'LITELLM_MODEL=gemini/gemini-3.1-pro-preview'],
                           'help_key': 'settings.ai_model.provider_keys',
                           'warning_codes': ['secret_value', 'comma_separated_keys']},
    'GEMINI_MODEL': {   'docs': [   {   'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/LLM_CONFIG_GUIDE.md',
                                        'label': 'LLM 配置指南'},
                                    {   'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/llm-providers.md',
                                        'label': 'LLM 服务商配置速查'}],
                        'examples': [   'GEMINI_MODEL=gemini-3.1-pro-preview',
                                        'LITELLM_MODEL=gemini/gemini-3.1-pro-preview'],
                        'help_key': 'settings.ai_model.legacy_provider_params',
                        'warning_codes': ['legacy_provider_setting']},
    'GEMINI_MODEL_FALLBACK': {   'docs': [   {   'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/LLM_CONFIG_GUIDE.md',
                                                 'label': 'LLM 配置指南'},
                                             {   'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/llm-providers.md',
                                                 'label': 'LLM 服务商配置速查'}],
                                 'examples': [   'GEMINI_MODEL_FALLBACK=gemini-3-flash-preview',
                                                 'LITELLM_FALLBACK_MODELS=gemini/gemini-3-flash-preview'],
                                 'help_key': 'settings.ai_model.legacy_provider_params',
                                 'warning_codes': ['legacy_provider_setting']},
    'GEMINI_TEMPERATURE': {   'docs': [   {   'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/LLM_CONFIG_GUIDE.md',
                                              'label': 'LLM 配置指南'},
                                          {   'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/llm-providers.md',
                                              'label': 'LLM 服务商配置速查'}],
                              'examples': ['GEMINI_TEMPERATURE=0.7', 'LLM_TEMPERATURE=0.7'],
                              'help_key': 'settings.ai_model.legacy_provider_params',
                              'warning_codes': ['legacy_provider_setting']},
    'GOTIFY_TOKEN': {   'docs': [   {   'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/full-guide.md#通知渠道详细配置',
                                        'label': '完整指南：通知渠道配置'}],
                        'examples': ['GOTIFY_TOKEN=your_gotify_token'],
                        'help_key': 'settings.notification.chat_bots',
                        'warning_codes': ['secret_value']},
    'GOTIFY_URL': {   'docs': [   {   'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/full-guide.md#通知渠道详细配置',
                                      'label': '完整指南：通知渠道配置'}],
                      'examples': ['GOTIFY_URL=https://gotify.example.com', 'GOTIFY_TOKEN=your_gotify_token'],
                      'help_key': 'settings.notification.chat_bots',
                      'warning_codes': ['webhook_secret_value']},
    'MINIMAX_API_KEYS': {   'docs': [   {   'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/full-guide.md#搜索服务配置',
                                            'label': '完整指南：搜索服务配置'}],
                            'examples': ['MINIMAX_API_KEYS=minimax_key_1,minimax_key_2'],
                            'help_key': 'settings.data_source.search_api_keys',
                            'warning_codes': ['secret_value', 'comma_separated_keys']},
    'NTFY_TOKEN': {   'docs': [   {   'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/full-guide.md#通知渠道详细配置',
                                      'label': '完整指南：通知渠道配置'}],
                      'examples': ['NTFY_TOKEN=your_ntfy_token'],
                      'help_key': 'settings.notification.chat_bots',
                      'warning_codes': ['secret_value']},
    'NTFY_URL': {   'docs': [   {   'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/full-guide.md#通知渠道详细配置',
                                    'label': '完整指南：通知渠道配置'}],
                    'examples': ['NTFY_URL=https://ntfy.sh/your_topic', 'NTFY_TOKEN=your_ntfy_token'],
                    'help_key': 'settings.notification.chat_bots',
                    'warning_codes': ['webhook_secret_value']},
    'OPENAI_API_KEYS': {   'docs': [   {   'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/LLM_CONFIG_GUIDE.md',
                                           'label': 'LLM 配置指南'},
                                       {   'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/llm-providers.md',
                                           'label': 'LLM 服务商配置速查'}],
                           'examples': [   'OPENAI_API_KEYS=sk-xxxx,sk-yyyy',
                                           'OPENAI_BASE_URL=https://api.example.com/v1'],
                           'help_key': 'settings.ai_model.provider_keys',
                           'warning_codes': ['secret_value', 'comma_separated_keys']},
    'OPENAI_MODEL': {   'docs': [   {   'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/LLM_CONFIG_GUIDE.md',
                                        'label': 'LLM 配置指南'},
                                    {   'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/llm-providers.md',
                                        'label': 'LLM 服务商配置速查'}],
                        'examples': ['OPENAI_MODEL=gpt-5.5', 'LITELLM_MODEL=openai/gpt-5.5'],
                        'help_key': 'settings.ai_model.legacy_provider_params',
                        'warning_codes': ['legacy_provider_setting']},
    'OPENAI_TEMPERATURE': {   'docs': [   {   'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/LLM_CONFIG_GUIDE.md',
                                              'label': 'LLM 配置指南'},
                                          {   'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/llm-providers.md',
                                              'label': 'LLM 服务商配置速查'}],
                              'examples': ['OPENAI_TEMPERATURE=0.7', 'LLM_TEMPERATURE=0.7'],
                              'help_key': 'settings.ai_model.legacy_provider_params',
                              'warning_codes': ['legacy_provider_setting']},
    'OPENAI_VISION_MODEL': {   'docs': [   {   'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/LLM_CONFIG_GUIDE.md',
                                               'label': 'LLM 配置指南'},
                                           {   'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/llm-providers.md',
                                               'label': 'LLM 服务商配置速查'}],
                               'examples': ['OPENAI_VISION_MODEL=gpt-5.5', 'VISION_MODEL=openai/gpt-5.5'],
                               'help_key': 'settings.ai_model.legacy_provider_params',
                               'warning_codes': ['legacy_provider_setting']},
    'PUSHOVER_API_TOKEN': {   'docs': [   {   'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/full-guide.md#通知渠道详细配置',
                                              'label': '完整指南：通知渠道配置'}],
                              'examples': ['PUSHOVER_API_TOKEN=your_pushover_api_token'],
                              'help_key': 'settings.notification.chat_bots',
                              'warning_codes': ['secret_value']},
    'PUSHOVER_USER_KEY': {   'docs': [   {   'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/full-guide.md#通知渠道详细配置',
                                             'label': '完整指南：通知渠道配置'}],
                             'examples': [   'PUSHOVER_USER_KEY=your_pushover_user_key',
                                             'PUSHOVER_API_TOKEN=your_pushover_api_token'],
                             'help_key': 'settings.notification.chat_bots',
                             'warning_codes': ['secret_value']},
    'PUSHPLUS_TOKEN': {   'docs': [   {   'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/full-guide.md#通知渠道详细配置',
                                          'label': '完整指南：通知渠道配置'}],
                          'examples': ['PUSHPLUS_TOKEN=your_pushplus_token', 'PUSHPLUS_TOPIC=your_pushplus_topic'],
                          'help_key': 'settings.notification.chat_bots',
                          'warning_codes': ['secret_value']},
    'PUSHPLUS_TOPIC': {   'docs': [   {   'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/full-guide.md#通知渠道详细配置',
                                          'label': '完整指南：通知渠道配置'}],
                          'examples': ['PUSHPLUS_TOPIC=your_pushplus_topic'],
                          'help_key': 'settings.notification.chat_bots',
                          'warning_codes': []},
    'PYTDX_HOST': {   'docs': [   {   'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/full-guide.md#数据源配置',
                                      'label': '完整指南：数据源配置'}],
                      'examples': ['PYTDX_HOST=119.147.212.81', 'PYTDX_PORT=7709'],
                      'help_key': 'settings.data_source.pytdx',
                      'warning_codes': []},
    'PYTDX_PORT': {   'docs': [   {   'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/full-guide.md#数据源配置',
                                      'label': '完整指南：数据源配置'}],
                      'examples': ['PYTDX_PORT=7709', 'PYTDX_HOST=119.147.212.81'],
                      'help_key': 'settings.data_source.pytdx',
                      'warning_codes': []},
    'PYTDX_SERVERS': {   'docs': [   {   'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/full-guide.md#数据源配置',
                                         'label': '完整指南：数据源配置'}],
                         'examples': ['PYTDX_SERVERS=119.147.212.81:7709,119.147.212.81:7711'],
                         'help_key': 'settings.data_source.pytdx',
                         'warning_codes': ['overrides_pytdx_host_port']},
    'SEARXNG_PUBLIC_INSTANCES_ENABLED': {   'docs': [   {   'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/full-guide.md#搜索服务配置',
                                                            'label': '完整指南：搜索服务配置'}],
                                            'examples': [   'SEARXNG_PUBLIC_INSTANCES_ENABLED=true',
                                                            'SEARXNG_PUBLIC_INSTANCES_ENABLED=false'],
                                            'help_key': 'settings.data_source.SEARXNG_BASE_URLS',
                                            'warning_codes': ['public_instance_stability']},
    'SERPAPI_API_KEYS': {   'docs': [   {   'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/full-guide.md#搜索服务配置',
                                            'label': '完整指南：搜索服务配置'}],
                            'examples': ['SERPAPI_API_KEYS=serpapi_key_1,serpapi_key_2'],
                            'help_key': 'settings.data_source.search_api_keys',
                            'warning_codes': ['secret_value', 'comma_separated_keys']},
    'SERVERCHAN3_SENDKEY': {   'docs': [   {   'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/full-guide.md#通知渠道详细配置',
                                               'label': '完整指南：通知渠道配置'}],
                               'examples': ['SERVERCHAN3_SENDKEY=your_serverchan3_sendkey'],
                               'help_key': 'settings.notification.chat_bots',
                               'warning_codes': ['secret_value']},
    'SLACK_CHANNEL_ID': {   'docs': [   {   'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/full-guide.md#通知渠道详细配置',
                                            'label': '完整指南：通知渠道配置'}],
                            'examples': ['SLACK_CHANNEL_ID=C0123456789'],
                            'help_key': 'settings.notification.chat_bots',
                            'warning_codes': []},
    'SLACK_WEBHOOK_URL': {   'docs': [   {   'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/full-guide.md#通知渠道详细配置',
                                             'label': '完整指南：通知渠道配置'}],
                             'examples': ['SLACK_WEBHOOK_URL=https://hooks.slack.com/services/xxx/yyy/zzz'],
                             'help_key': 'settings.notification.chat_bots',
                             'warning_codes': ['webhook_secret_value']},
    'TELEGRAM_MESSAGE_THREAD_ID': {   'docs': [   {   'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/full-guide.md#通知渠道详细配置',
                                                      'label': '完整指南：通知渠道配置'}],
                                      'examples': ['TELEGRAM_MESSAGE_THREAD_ID=123'],
                                      'help_key': 'settings.notification.telegram',
                                      'warning_codes': []},
    'TICKFLOW_API_KEY': {   'docs': [   {   'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/full-guide.md#数据源配置',
                                            'label': '完整指南：数据源配置'}],
                            'examples': ['TICKFLOW_API_KEY=your_tickflow_key'],
                            'help_key': 'settings.data_source.TICKFLOW_API_KEY',
                            'warning_codes': ['secret_value']}}
