"""
字段定义 - notification 分类
从 config_registry.py 按 category 拆分
"""

FIELD_DEFINITIONS: dict = {
    "WECHAT_WEBHOOK_URL": {       'category': 'notification',
        'data_type': 'string',
        'default_value': None,
        'description': 'Webhook URL for enterprise WeChat bot.',
        'display_order': 10,
        'docs': [       {       'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/full-guide.md#通知渠道详细配置',
                                'label': '完整指南：通知渠道配置'}],
        'examples': ['WECHAT_WEBHOOK_URL=https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=xxxx'],
        'help_key': 'settings.notification.webhooks',
        'is_editable': True,
        'is_required': False,
        'is_sensitive': True,
        'options': [],
        'title': 'WeChat Webhook URL',
        'ui_control': 'password',
        'validation': {},
        'warning_codes': ['webhook_secret_value']},
    "DINGTALK_APP_KEY": {       'category': 'notification',
        'data_type': 'string',
        'default_value': None,
        'description': 'DingTalk app key.',
        'display_order': 20,
        'is_editable': True,
        'is_required': False,
        'is_sensitive': True,
        'options': [],
        'title': 'DingTalk App Key',
        'ui_control': 'password',
        'validation': {}},
    "DINGTALK_APP_SECRET": {       'category': 'notification',
        'data_type': 'string',
        'default_value': None,
        'description': 'DingTalk app secret.',
        'display_order': 30,
        'is_editable': True,
        'is_required': False,
        'is_sensitive': True,
        'options': [],
        'title': 'DingTalk App Secret',
        'ui_control': 'password',
        'validation': {}},
    "DINGTALK_STREAM_ENABLED": {       'category': 'notification',
        'data_type': 'boolean',
        'default_value': 'false',
        'description': 'Enable DingTalk application bot stream/long-connection mode. This is separate from DingTalk '
                       'group webhook delivery.',
        'display_order': 35,
        'docs': [       {       'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/full-guide.md#通知渠道详细配置',
                                'label': '完整指南：通知渠道配置'}],
        'examples': [       'DINGTALK_STREAM_ENABLED=false',
                            'DINGTALK_STREAM_ENABLED=true',
                            'DINGTALK_APP_KEY=your_dingtalk_app_key',
                            'DINGTALK_APP_SECRET=your_dingtalk_app_secret'],
        'help_key': 'settings.notification.DINGTALK_STREAM_ENABLED',
        'is_editable': True,
        'is_required': False,
        'is_sensitive': False,
        'options': [],
        'title': 'DingTalk Stream Mode',
        'ui_control': 'switch',
        'validation': {},
        'warning_codes': ['not_webhook_delivery', 'restart_required']},
    "PUSHPLUS_TOKEN": {       'category': 'notification',
        'data_type': 'string',
        'default_value': None,
        'description': 'Token for PushPlus notifications.',
        'display_order': 40,
        'is_editable': True,
        'is_required': False,
        'is_sensitive': True,
        'options': [],
        'title': 'PushPlus Token',
        'ui_control': 'password',
        'validation': {}},
    "CUSTOM_WEBHOOK_URLS": {       'category': 'notification',
        'data_type': 'array',
        'default_value': None,
        'description': 'Comma-separated webhook URLs for custom notifications (DingTalk, Bark, Discord, Slack, etc.).',
        'display_order': 50,
        'docs': [       {       'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/full-guide.md#自定义-webhook',
                                'label': '完整指南：自定义 Webhook'}],
        'examples': [       'CUSTOM_WEBHOOK_URLS=https://api.day.app/YOUR_BARK_KEY',
                            'CUSTOM_WEBHOOK_URLS=https://oapi.dingtalk.com/robot/send?access_token=xxx',
                            'CUSTOM_WEBHOOK_BODY_TEMPLATE={"msg_type":"text","content":$content_json}'],
        'help_key': 'settings.notification.CUSTOM_WEBHOOK_URLS',
        'is_editable': True,
        'is_required': False,
        'is_sensitive': False,
        'options': [],
        'title': 'Custom Webhook URLs',
        'ui_control': 'textarea',
        'validation': {'delimiter': ',', 'multi_value': True},
        'warning_codes': ['json_template_must_render_object']},
    "CUSTOM_WEBHOOK_BEARER_TOKEN": {       'category': 'notification',
        'data_type': 'string',
        'default_value': None,
        'description': 'Bearer token for authenticated custom webhooks.',
        'display_order': 51,
        'is_editable': True,
        'is_required': False,
        'is_sensitive': True,
        'options': [],
        'title': 'Custom Webhook Bearer Token',
        'ui_control': 'password',
        'validation': {}},
    "CUSTOM_WEBHOOK_BODY_TEMPLATE": {       'category': 'notification',
        'data_type': 'string',
        'default_value': None,
        'description': 'Optional global JSON body template for custom webhooks. It is rendered before URL '
                       'auto-detected payloads such as Bark, Slack, or Discord, and must render to a JSON object. '
                       'Prefer $content_json and $title_json; raw $content and $title are not JSON-escaped and can '
                       'make the template invalid.',
        'display_order': 52,
        'is_editable': True,
        'is_required': False,
        'is_sensitive': False,
        'options': [],
        'title': 'Custom Webhook Body Template',
        'ui_control': 'textarea',
        'validation': {}},
    "WEBHOOK_VERIFY_SSL": {       'category': 'notification',
        'data_type': 'boolean',
        'default_value': 'true',
        'description': 'Verify HTTPS certificates for webhook requests. Set to false ONLY for self-signed certs in '
                       'trusted internal networks. WARNING: Disabling allows MITM attacks—do NOT use on public '
                       'networks.',
        'display_order': 53,
        'docs': [       {       'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/full-guide.md#自定义-webhook',
                                'label': '完整指南：自定义 Webhook'}],
        'examples': ['WEBHOOK_VERIFY_SSL=true', 'WEBHOOK_VERIFY_SSL=false'],
        'help_key': 'settings.notification.WEBHOOK_VERIFY_SSL',
        'is_editable': True,
        'is_required': False,
        'is_sensitive': False,
        'options': [],
        'title': 'Webhook SSL Verify',
        'ui_control': 'switch',
        'validation': {},
        'warning_codes': ['disabling_ssl_verify_is_risky']},
    "REPORT_SUMMARY_ONLY": {       'category': 'notification',
        'data_type': 'boolean',
        'default_value': 'false',
        'description': 'Push only analysis summary without per-stock details. Suitable for quick overview when '
                       'tracking many stocks (Issue #262).',
        'display_order': 53,
        'docs': [       {       'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/full-guide.md#环境变量完整列表',
                                'label': '完整指南：环境变量完整列表'}],
        'examples': ['REPORT_SUMMARY_ONLY=true', 'REPORT_SUMMARY_ONLY=false'],
        'help_key': 'settings.report.REPORT_SUMMARY_ONLY',
        'is_editable': True,
        'is_required': False,
        'is_sensitive': False,
        'options': [],
        'title': 'Report Summary Only',
        'ui_control': 'switch',
        'validation': {},
        'warning_codes': []},
    "REPORT_SHOW_LLM_MODEL": {       'category': 'notification',
        'data_type': 'boolean',
        'default_value': 'true',
        'description': 'Show the LLM model name in notification report footers. Disable to hide runtime model '
                       'metadata. This option only affects report rendering and does not change runtime '
                       'provider/model/Base URL/LiteLLM routing, migration, persistence, or cleanup behavior.',
        'display_order': 54,
        'docs': [       {       'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/full-guide.md#环境变量完整列表',
                                'label': '完整指南：环境变量完整列表'}],
        'examples': ['REPORT_SHOW_LLM_MODEL=true', 'REPORT_SHOW_LLM_MODEL=false'],
        'help_key': 'settings.report.REPORT_SHOW_LLM_MODEL',
        'is_editable': True,
        'is_required': False,
        'is_sensitive': False,
        'options': [],
        'title': 'Show LLM Model in Reports',
        'ui_control': 'switch',
        'validation': {},
        'warning_codes': []},
    "FEISHU_WEBHOOK_URL": {       'category': 'notification',
        'data_type': 'string',
        'default_value': None,
        'description': 'Feishu custom bot webhook URL for group notifications. This is the webhook push channel; '
                       'FEISHU_APP_ID / FEISHU_APP_SECRET do not enable webhook delivery by themselves.',
        'display_order': 12,
        'docs': [       {       'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/full-guide.md#飞书',
                                'label': '完整指南：飞书通知配置'},
                        {       'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/bot/feishu-bot-config.md',
                                'label': '飞书机器人配置专题'}],
        'examples': [       'FEISHU_WEBHOOK_URL=https://open.feishu.cn/open-apis/bot/v2/hook/your_hook_token',
                            'FEISHU_WEBHOOK_SECRET=your_feishu_webhook_secret',
                            'FEISHU_WEBHOOK_KEYWORD=股票日报'],
        'help_key': 'settings.notification.FEISHU_WEBHOOK_URL',
        'is_editable': True,
        'is_required': False,
        'is_sensitive': True,
        'options': [],
        'title': 'Feishu Webhook URL',
        'ui_control': 'password',
        'validation': {'allowed_schemes': ['http', 'https'], 'item_type': 'url'},
        'warning_codes': ['feishu_webhook_not_app_secret']},
    "FEISHU_WEBHOOK_SECRET": {       'category': 'notification',
        'data_type': 'string',
        'default_value': None,
        'description': 'Optional signing secret from Feishu custom bot security settings. Only used for webhook push '
                       'mode.',
        'display_order': 13,
        'is_editable': True,
        'is_required': False,
        'is_sensitive': True,
        'options': [],
        'title': 'Feishu Webhook Secret',
        'ui_control': 'password',
        'validation': {}},
    "FEISHU_WEBHOOK_KEYWORD": {       'category': 'notification',
        'data_type': 'string',
        'default_value': None,
        'description': 'Optional keyword required by Feishu custom bot security settings. The sender prepends it to '
                       'every webhook message.',
        'display_order': 14,
        'is_editable': True,
        'is_required': False,
        'is_sensitive': False,
        'options': [],
        'title': 'Feishu Webhook Keyword',
        'ui_control': 'text',
        'validation': {}},
    "FEISHU_APP_ID": {       'category': 'notification',
        'data_type': 'string',
        'default_value': None,
        'description': 'Feishu app bot App ID for app/stream bot mode or cloud documents. It does not enable group '
                       'webhook push by itself.',
        'display_order': 15,
        'is_editable': True,
        'is_required': False,
        'is_sensitive': False,
        'options': [],
        'title': 'Feishu App ID',
        'ui_control': 'text',
        'validation': {}},
    "FEISHU_APP_SECRET": {       'category': 'notification',
        'data_type': 'string',
        'default_value': None,
        'description': 'Feishu app bot App Secret for app/stream bot mode or cloud documents. It does not enable group '
                       'webhook push by itself.',
        'display_order': 16,
        'is_editable': True,
        'is_required': False,
        'is_sensitive': True,
        'options': [],
        'title': 'Feishu App Secret',
        'ui_control': 'password',
        'validation': {}},
    "FEISHU_STREAM_ENABLED": {       'category': 'notification',
        'data_type': 'boolean',
        'default_value': 'false',
        'description': 'Enable Feishu application bot stream mode. This is separate from Feishu group webhook '
                       'delivery.',
        'display_order': 17,
        'docs': [       {       'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/full-guide.md#飞书',
                                'label': '完整指南：飞书通知配置'},
                        {       'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/bot/feishu-bot-config.md',
                                'label': '飞书机器人配置专题'}],
        'examples': [       'FEISHU_STREAM_ENABLED=false',
                            'FEISHU_STREAM_ENABLED=true',
                            'FEISHU_APP_ID=cli_xxxxx',
                            'FEISHU_APP_SECRET=your_feishu_app_secret'],
        'help_key': 'settings.notification.FEISHU_STREAM_ENABLED',
        'is_editable': True,
        'is_required': False,
        'is_sensitive': False,
        'options': [],
        'title': 'Feishu Stream Mode',
        'ui_control': 'switch',
        'validation': {},
        'warning_codes': ['not_webhook_delivery', 'restart_required']},
    "TELEGRAM_BOT_TOKEN": {       'category': 'notification',
        'data_type': 'string',
        'default_value': None,
        'description': 'Telegram bot token (from @BotFather).',
        'display_order': 17,
        'docs': [       {       'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/full-guide.md#telegram',
                                'label': '完整指南：Telegram'}],
        'examples': ['TELEGRAM_BOT_TOKEN=123456:ABC-DEF', 'TELEGRAM_CHAT_ID=-1001234567890'],
        'help_key': 'settings.notification.telegram',
        'is_editable': True,
        'is_required': False,
        'is_sensitive': True,
        'options': [],
        'title': 'Telegram Bot Token',
        'ui_control': 'password',
        'validation': {},
        'warning_codes': ['secret_value']},
    "TELEGRAM_CHAT_ID": {       'category': 'notification',
        'data_type': 'string',
        'default_value': None,
        'description': 'Telegram chat/group ID to send messages to.',
        'display_order': 18,
        'docs': [       {       'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/full-guide.md#telegram',
                                'label': '完整指南：Telegram'}],
        'examples': ['TELEGRAM_CHAT_ID=-1001234567890', 'TELEGRAM_MESSAGE_THREAD_ID=123'],
        'help_key': 'settings.notification.telegram',
        'is_editable': True,
        'is_required': False,
        'is_sensitive': False,
        'options': [],
        'title': 'Telegram Chat ID',
        'ui_control': 'text',
        'validation': {},
        'warning_codes': []},
    "TELEGRAM_MESSAGE_THREAD_ID": {       'category': 'notification',
        'data_type': 'string',
        'default_value': None,
        'description': 'Telegram topic/thread ID for group messages (optional).',
        'display_order': 19,
        'is_editable': True,
        'is_required': False,
        'is_sensitive': False,
        'options': [],
        'title': 'Telegram Thread ID',
        'ui_control': 'text',
        'validation': {}},
    "EMAIL_SENDER": {       'category': 'notification',
        'data_type': 'string',
        'default_value': None,
        'description': 'Sender email address (SMTP host auto-detected).',
        'display_order': 25,
        'docs': [       {       'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/full-guide.md#邮件',
                                'label': '完整指南：邮件'}],
        'examples': [       'EMAIL_SENDER=sender@example.com',
                            'EMAIL_PASSWORD=your_smtp_authorization_code',
                            'EMAIL_RECEIVERS=user1@example.com,user2@example.com'],
        'help_key': 'settings.notification.email',
        'is_editable': True,
        'is_required': False,
        'is_sensitive': False,
        'options': [],
        'title': 'Email Sender',
        'ui_control': 'text',
        'validation': {},
        'warning_codes': []},
    "EMAIL_PASSWORD": {       'category': 'notification',
        'data_type': 'string',
        'default_value': None,
        'description': 'Email password or app-specific authorization code.',
        'display_order': 26,
        'docs': [       {       'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/full-guide.md#邮件',
                                'label': '完整指南：邮件'}],
        'examples': ['EMAIL_PASSWORD=your_smtp_authorization_code'],
        'help_key': 'settings.notification.email',
        'is_editable': True,
        'is_required': False,
        'is_sensitive': True,
        'options': [],
        'title': 'Email Password',
        'ui_control': 'password',
        'validation': {},
        'warning_codes': ['secret_value', 'smtp_authorization_code']},
    "EMAIL_RECEIVERS": {       'category': 'notification',
        'data_type': 'array',
        'default_value': None,
        'description': 'Comma-separated recipient email addresses. Leave empty to send to yourself.',
        'display_order': 27,
        'docs': [       {       'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/full-guide.md#邮件',
                                'label': '完整指南：邮件'}],
        'examples': [       'EMAIL_RECEIVERS=user1@example.com,user2@example.com',
                            'STOCK_GROUP_1=600519,300750',
                            'EMAIL_GROUP_1=user1@example.com'],
        'help_key': 'settings.notification.email',
        'is_editable': True,
        'is_required': False,
        'is_sensitive': False,
        'options': [],
        'title': 'Email Receivers',
        'ui_control': 'textarea',
        'validation': {'delimiter': ',', 'multi_value': True},
        'warning_codes': ['comma_separated_values']},
    "DISCORD_WEBHOOK_URL": {       'category': 'notification',
        'data_type': 'string',
        'default_value': None,
        'description': 'Discord webhook URL for channel notifications.',
        'display_order': 33,
        'docs': [       {       'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/full-guide.md#discord',
                                'label': '完整指南：Discord'}],
        'examples': ['DISCORD_WEBHOOK_URL=https://discord.com/api/webhooks/xxx/yyy'],
        'help_key': 'settings.notification.chat_bots',
        'is_editable': True,
        'is_required': False,
        'is_sensitive': True,
        'options': [],
        'title': 'Discord Webhook URL',
        'ui_control': 'password',
        'validation': {},
        'warning_codes': ['webhook_secret_value']},
    "DISCORD_BOT_TOKEN": {       'category': 'notification',
        'data_type': 'string',
        'default_value': None,
        'description': 'Discord bot token for interactive bot mode.',
        'display_order': 34,
        'docs': [       {       'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/full-guide.md#discord',
                                'label': '完整指南：Discord'}],
        'examples': ['DISCORD_BOT_TOKEN=your_discord_bot_token', 'DISCORD_MAIN_CHANNEL_ID=123456789012345678'],
        'help_key': 'settings.notification.chat_bots',
        'is_editable': True,
        'is_required': False,
        'is_sensitive': True,
        'options': [],
        'title': 'Discord Bot Token',
        'ui_control': 'password',
        'validation': {},
        'warning_codes': ['secret_value']},
    "DISCORD_MAIN_CHANNEL_ID": {       'category': 'notification',
        'data_type': 'string',
        'default_value': None,
        'description': 'Discord main channel ID for sending messages.',
        'display_order': 35,
        'is_editable': True,
        'is_required': False,
        'is_sensitive': False,
        'options': [],
        'title': 'Discord Channel ID',
        'ui_control': 'text',
        'validation': {}},
    "DISCORD_INTERACTIONS_PUBLIC_KEY": {       'category': 'notification',
        'data_type': 'string',
        'default_value': None,
        'description': 'Discord public key used to verify inbound interaction/webhook signatures.',
        'display_order': 36,
        'is_editable': True,
        'is_required': False,
        'is_sensitive': False,
        'options': [],
        'title': 'Discord Interactions Public Key',
        'ui_control': 'text',
        'validation': {}},
    "SLACK_BOT_TOKEN": {       'category': 'notification',
        'data_type': 'string',
        'default_value': None,
        'description': 'Slack Bot Token (xoxb-...). Recommended; supports image upload. Takes priority over Webhook '
                       'when both are configured.',
        'display_order': 37,
        'docs': [       {       'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/full-guide.md#通知渠道详细配置',
                                'label': '完整指南：通知渠道配置'}],
        'examples': ['SLACK_BOT_TOKEN=xoxb-xxxx', 'SLACK_CHANNEL_ID=C0123456789'],
        'help_key': 'settings.notification.chat_bots',
        'is_editable': True,
        'is_required': False,
        'is_sensitive': True,
        'options': [],
        'title': 'Slack Bot Token',
        'ui_control': 'password',
        'validation': {},
        'warning_codes': ['secret_value']},
    "SLACK_CHANNEL_ID": {       'category': 'notification',
        'data_type': 'string',
        'default_value': None,
        'description': 'Slack channel ID (required when using Bot Token).',
        'display_order': 38,
        'is_editable': True,
        'is_required': False,
        'is_sensitive': False,
        'options': [],
        'title': 'Slack Channel ID',
        'ui_control': 'text',
        'validation': {}},
    "SLACK_WEBHOOK_URL": {       'category': 'notification',
        'data_type': 'string',
        'default_value': None,
        'description': 'Slack Incoming Webhook URL (text only, no image support).',
        'display_order': 39,
        'is_editable': True,
        'is_required': False,
        'is_sensitive': True,
        'options': [],
        'title': 'Slack Incoming Webhook URL',
        'ui_control': 'password',
        'validation': {}},
    "PUSHOVER_USER_KEY": {       'category': 'notification',
        'data_type': 'string',
        'default_value': None,
        'description': 'Pushover user key (from https://pushover.net).',
        'display_order': 42,
        'is_editable': True,
        'is_required': False,
        'is_sensitive': True,
        'options': [],
        'title': 'Pushover User Key',
        'ui_control': 'password',
        'validation': {}},
    "PUSHOVER_API_TOKEN": {       'category': 'notification',
        'data_type': 'string',
        'default_value': None,
        'description': 'Pushover application API token.',
        'display_order': 43,
        'is_editable': True,
        'is_required': False,
        'is_sensitive': True,
        'options': [],
        'title': 'Pushover API Token',
        'ui_control': 'password',
        'validation': {}},
    "NTFY_URL": {       'category': 'notification',
        'data_type': 'string',
        'default_value': None,
        'description': 'Full ntfy publish endpoint including topic path, e.g. https://ntfy.sh/my-topic.',
        'display_order': 44,
        'is_editable': True,
        'is_required': False,
        'is_sensitive': True,
        'options': [],
        'title': 'ntfy URL',
        'ui_control': 'password',
        'validation': {'allowed_schemes': ['http', 'https'], 'item_type': 'url'}},
    "NTFY_TOKEN": {       'category': 'notification',
        'data_type': 'string',
        'default_value': None,
        'description': 'Optional ntfy bearer token for protected topics or self-hosted servers.',
        'display_order': 45,
        'is_editable': True,
        'is_required': False,
        'is_sensitive': True,
        'options': [],
        'title': 'ntfy Token',
        'ui_control': 'password',
        'validation': {}},
    "GOTIFY_URL": {       'category': 'notification',
        'data_type': 'string',
        'default_value': None,
        'description': 'Gotify server base URL. Do not include /message; the sender appends it.',
        'display_order': 46,
        'is_editable': True,
        'is_required': False,
        'is_sensitive': True,
        'options': [],
        'title': 'Gotify URL',
        'ui_control': 'password',
        'validation': {'allowed_schemes': ['http', 'https'], 'item_type': 'url'}},
    "GOTIFY_TOKEN": {       'category': 'notification',
        'data_type': 'string',
        'default_value': None,
        'description': 'Gotify application token sent via the X-Gotify-Key header.',
        'display_order': 47,
        'is_editable': True,
        'is_required': False,
        'is_sensitive': True,
        'options': [],
        'title': 'Gotify Token',
        'ui_control': 'password',
        'validation': {}},
    "PUSHPLUS_TOPIC": {       'category': 'notification',
        'data_type': 'string',
        'default_value': None,
        'description': 'PushPlus group topic code for one-to-many push.',
        'display_order': 41,
        'is_editable': True,
        'is_required': False,
        'is_sensitive': False,
        'options': [],
        'title': 'PushPlus Topic',
        'ui_control': 'text',
        'validation': {}},
    "SERVERCHAN3_SENDKEY": {       'category': 'notification',
        'data_type': 'string',
        'default_value': None,
        'description': 'Server酱3 SendKey for push notifications.',
        'display_order': 46,
        'is_editable': True,
        'is_required': False,
        'is_sensitive': True,
        'options': [],
        'title': 'ServerChan3 SendKey',
        'ui_control': 'password',
        'validation': {}},
    "ASTRBOT_URL": {       'category': 'notification',
        'data_type': 'string',
        'default_value': None,
        'description': 'AstrBot webhook endpoint URL.',
        'display_order': 47,
        'is_editable': True,
        'is_required': False,
        'is_sensitive': True,
        'options': [],
        'title': 'AstrBot URL',
        'ui_control': 'password',
        'validation': {'allowed_schemes': ['http', 'https'], 'item_type': 'url'}},
    "ASTRBOT_TOKEN": {       'category': 'notification',
        'data_type': 'string',
        'default_value': None,
        'description': 'Optional AstrBot bearer token.',
        'display_order': 48,
        'is_editable': True,
        'is_required': False,
        'is_sensitive': True,
        'options': [],
        'title': 'AstrBot Token',
        'ui_control': 'password',
        'validation': {}},
    "SINGLE_STOCK_NOTIFY": {       'category': 'notification',
        'data_type': 'boolean',
        'default_value': 'false',
        'description': 'Push immediately after each single stock analysis instead of batching all results together.',
        'display_order': 54,
        'docs': [       {       'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/full-guide.md#环境变量完整列表',
                                'label': '完整指南：环境变量完整列表'}],
        'examples': ['SINGLE_STOCK_NOTIFY=true', 'SINGLE_STOCK_NOTIFY=false'],
        'help_key': 'settings.report.SINGLE_STOCK_NOTIFY',
        'is_editable': True,
        'is_required': False,
        'is_sensitive': False,
        'options': [],
        'title': 'Single Stock Notify',
        'ui_control': 'switch',
        'validation': {},
        'warning_codes': []},
    "REPORT_TYPE": {       'category': 'notification',
        'data_type': 'string',
        'default_value': 'simple',
        'description': "Report format: 'simple' (concise), 'full' (detailed), or 'brief' (3-5 sentences).",
        'display_order': 55,
        'docs': [       {       'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/full-guide.md#环境变量完整列表',
                                'label': '完整指南：环境变量完整列表'}],
        'examples': ['REPORT_TYPE=simple', 'REPORT_TYPE=full', 'REPORT_LANGUAGE=zh'],
        'help_key': 'settings.notification.report_output',
        'is_editable': True,
        'is_required': False,
        'is_sensitive': False,
        'options': ['simple', 'full', 'brief'],
        'title': 'Report Type',
        'ui_control': 'select',
        'validation': {'enum': ['simple', 'full', 'brief']},
        'warning_codes': []},
    "REPORT_LANGUAGE": {       'category': 'notification',
        'data_type': 'string',
        'default_value': 'zh',
        'description': 'Default output language for reports and notification templates. Supported values: zh, en.',
        'display_order': 56,
        'docs': [       {       'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/full-guide.md#环境变量完整列表',
                                'label': '完整指南：环境变量完整列表'}],
        'examples': ['REPORT_LANGUAGE=zh', 'REPORT_LANGUAGE=en'],
        'help_key': 'settings.notification.report_output',
        'is_editable': True,
        'is_required': False,
        'is_sensitive': False,
        'options': [{'label': 'Chinese', 'value': 'zh'}, {'label': 'English', 'value': 'en'}],
        'title': 'Report Language',
        'ui_control': 'select',
        'validation': {'enum': ['zh', 'en']},
        'warning_codes': []},
    "REPORT_TEMPLATES_DIR": {       'category': 'notification',
        'data_type': 'string',
        'default_value': 'templates',
        'description': 'Directory for Jinja2 report templates (relative to project root).',
        'display_order': 57,
        'docs': [       {       'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/full-guide.md#环境变量完整列表',
                                'label': '完整指南：环境变量完整列表'}],
        'examples': ['REPORT_TEMPLATES_DIR=templates', 'REPORT_TEMPLATES_DIR=custom_templates'],
        'help_key': 'settings.report.REPORT_TEMPLATES_DIR',
        'is_editable': True,
        'is_required': False,
        'is_sensitive': False,
        'options': [],
        'title': 'Report Templates Dir',
        'ui_control': 'text',
        'validation': {},
        'warning_codes': []},
    "REPORT_RENDERER_ENABLED": {       'category': 'notification',
        'data_type': 'boolean',
        'default_value': 'false',
        'description': 'Enable Jinja2 template rendering for reports. Default false for zero regression.',
        'display_order': 58,
        'docs': [       {       'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/full-guide.md#环境变量完整列表',
                                'label': '完整指南：环境变量完整列表'}],
        'examples': ['REPORT_RENDERER_ENABLED=true', 'REPORT_RENDERER_ENABLED=false'],
        'help_key': 'settings.report.REPORT_RENDERER_ENABLED',
        'is_editable': True,
        'is_required': False,
        'is_sensitive': False,
        'options': [],
        'title': 'Report Renderer Enabled',
        'ui_control': 'switch',
        'validation': {},
        'warning_codes': []},
    "REPORT_INTEGRITY_ENABLED": {       'category': 'notification',
        'data_type': 'boolean',
        'default_value': 'true',
        'description': 'Validate mandatory report fields after LLM output; retry or placeholder on missing.',
        'display_order': 58,
        'docs': [       {       'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/full-guide.md#环境变量完整列表',
                                'label': '完整指南：环境变量完整列表'}],
        'examples': ['REPORT_INTEGRITY_ENABLED=true', 'REPORT_INTEGRITY_RETRY=1'],
        'help_key': 'settings.report.REPORT_INTEGRITY_ENABLED',
        'is_editable': True,
        'is_required': False,
        'is_sensitive': False,
        'options': [],
        'title': 'Report Integrity Enabled',
        'ui_control': 'switch',
        'validation': {},
        'warning_codes': []},
    "REPORT_INTEGRITY_RETRY": {       'category': 'notification',
        'data_type': 'integer',
        'default_value': '1',
        'description': 'Retry count when mandatory fields missing (0 = placeholder only, no retry).',
        'display_order': 59,
        'docs': [       {       'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/full-guide.md#环境变量完整列表',
                                'label': '完整指南：环境变量完整列表'}],
        'examples': ['REPORT_INTEGRITY_RETRY=1', 'REPORT_INTEGRITY_RETRY=0'],
        'help_key': 'settings.report.REPORT_INTEGRITY_ENABLED',
        'is_editable': True,
        'is_required': False,
        'is_sensitive': False,
        'options': [],
        'title': 'Report Integrity Retry',
        'ui_control': 'number',
        'validation': {'max': 3, 'min': 0},
        'warning_codes': []},
    "REPORT_HISTORY_COMPARE_N": {       'category': 'notification',
        'data_type': 'integer',
        'default_value': '0',
        'description': 'Show last N analyses signal comparison per stock (0 = disabled).',
        'display_order': 60,
        'docs': [       {       'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/full-guide.md#环境变量完整列表',
                                'label': '完整指南：环境变量完整列表'}],
        'examples': ['REPORT_HISTORY_COMPARE_N=0', 'REPORT_HISTORY_COMPARE_N=5'],
        'help_key': 'settings.report.REPORT_HISTORY_COMPARE_N',
        'is_editable': True,
        'is_required': False,
        'is_sensitive': False,
        'options': [],
        'title': 'Report History Compare N',
        'ui_control': 'number',
        'validation': {'max': 10, 'min': 0},
        'warning_codes': []},
    "MERGE_EMAIL_NOTIFICATION": {       'category': 'notification',
        'data_type': 'boolean',
        'default_value': 'false',
        'description': 'Merge stock analysis and market review into a single email notification.',
        'display_order': 61,
        'docs': [       {       'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/full-guide.md#环境变量完整列表',
                                'label': '完整指南：环境变量完整列表'}],
        'examples': ['MERGE_EMAIL_NOTIFICATION=true', 'MERGE_EMAIL_NOTIFICATION=false'],
        'help_key': 'settings.report.MERGE_EMAIL_NOTIFICATION',
        'is_editable': True,
        'is_required': False,
        'is_sensitive': False,
        'options': [],
        'title': 'Merge Email Notification',
        'ui_control': 'switch',
        'validation': {},
        'warning_codes': []},
    "NOTIFICATION_REPORT_CHANNELS": {       'category': 'notification',
        'data_type': 'array',
        'default_value': '',
        'description': 'Comma-separated route for report notifications. Empty keeps all configured channels.',
        'display_order': 62,
        'docs': [       {       'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/notifications.md',
                                'label': '通知渠道与路由'}],
        'examples': ['NOTIFICATION_REPORT_CHANNELS=email,feishu', 'NOTIFICATION_REPORT_CHANNELS='],
        'help_key': 'settings.notification.channel_routing',
        'is_editable': True,
        'is_required': False,
        'is_sensitive': False,
        'options': [       {'label': 'wechat', 'value': 'wechat'},
                           {'label': 'feishu', 'value': 'feishu'},
                           {'label': 'telegram', 'value': 'telegram'},
                           {'label': 'email', 'value': 'email'},
                           {'label': 'pushover', 'value': 'pushover'},
                           {'label': 'ntfy', 'value': 'ntfy'},
                           {'label': 'gotify', 'value': 'gotify'},
                           {'label': 'pushplus', 'value': 'pushplus'},
                           {'label': 'serverchan3', 'value': 'serverchan3'},
                           {'label': 'custom', 'value': 'custom'},
                           {'label': 'discord', 'value': 'discord'},
                           {'label': 'slack', 'value': 'slack'},
                           {'label': 'astrbot', 'value': 'astrbot'}],
        'title': 'Report Notification Channels',
        'ui_control': 'textarea',
        'validation': {       'allowed_values': [       'wechat',
                                                        'feishu',
                                                        'telegram',
                                                        'email',
                                                        'pushover',
                                                        'ntfy',
                                                        'gotify',
                                                        'pushplus',
                                                        'serverchan3',
                                                        'custom',
                                                        'discord',
                                                        'slack',
                                                        'astrbot'],
                              'delimiter': ','},
        'warning_codes': []},
    "NOTIFICATION_ALERT_CHANNELS": {       'category': 'notification',
        'data_type': 'array',
        'default_value': '',
        'description': 'Comma-separated route for event alert notifications. Empty keeps all configured channels.',
        'display_order': 63,
        'docs': [       {       'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/notifications.md',
                                'label': '通知渠道与路由'}],
        'examples': ['NOTIFICATION_ALERT_CHANNELS=feishu,telegram', 'NOTIFICATION_ALERT_CHANNELS='],
        'help_key': 'settings.notification.channel_routing',
        'is_editable': True,
        'is_required': False,
        'is_sensitive': False,
        'options': [       {'label': 'wechat', 'value': 'wechat'},
                           {'label': 'feishu', 'value': 'feishu'},
                           {'label': 'telegram', 'value': 'telegram'},
                           {'label': 'email', 'value': 'email'},
                           {'label': 'pushover', 'value': 'pushover'},
                           {'label': 'ntfy', 'value': 'ntfy'},
                           {'label': 'gotify', 'value': 'gotify'},
                           {'label': 'pushplus', 'value': 'pushplus'},
                           {'label': 'serverchan3', 'value': 'serverchan3'},
                           {'label': 'custom', 'value': 'custom'},
                           {'label': 'discord', 'value': 'discord'},
                           {'label': 'slack', 'value': 'slack'},
                           {'label': 'astrbot', 'value': 'astrbot'}],
        'title': 'Alert Notification Channels',
        'ui_control': 'textarea',
        'validation': {       'allowed_values': [       'wechat',
                                                        'feishu',
                                                        'telegram',
                                                        'email',
                                                        'pushover',
                                                        'ntfy',
                                                        'gotify',
                                                        'pushplus',
                                                        'serverchan3',
                                                        'custom',
                                                        'discord',
                                                        'slack',
                                                        'astrbot'],
                              'delimiter': ','},
        'warning_codes': []},
    "NOTIFICATION_SYSTEM_ERROR_CHANNELS": {       'category': 'notification',
        'data_type': 'array',
        'default_value': '',
        'description': 'Comma-separated route reserved for system error notifications. Empty keeps all configured '
                       'channels.',
        'display_order': 64,
        'docs': [       {       'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/notifications.md',
                                'label': '通知渠道与路由'}],
        'examples': ['NOTIFICATION_SYSTEM_ERROR_CHANNELS=email', 'NOTIFICATION_SYSTEM_ERROR_CHANNELS='],
        'help_key': 'settings.notification.channel_routing',
        'is_editable': True,
        'is_required': False,
        'is_sensitive': False,
        'options': [       {'label': 'wechat', 'value': 'wechat'},
                           {'label': 'feishu', 'value': 'feishu'},
                           {'label': 'telegram', 'value': 'telegram'},
                           {'label': 'email', 'value': 'email'},
                           {'label': 'pushover', 'value': 'pushover'},
                           {'label': 'ntfy', 'value': 'ntfy'},
                           {'label': 'gotify', 'value': 'gotify'},
                           {'label': 'pushplus', 'value': 'pushplus'},
                           {'label': 'serverchan3', 'value': 'serverchan3'},
                           {'label': 'custom', 'value': 'custom'},
                           {'label': 'discord', 'value': 'discord'},
                           {'label': 'slack', 'value': 'slack'},
                           {'label': 'astrbot', 'value': 'astrbot'}],
        'title': 'System Error Notification Channels',
        'ui_control': 'textarea',
        'validation': {       'allowed_values': [       'wechat',
                                                        'feishu',
                                                        'telegram',
                                                        'email',
                                                        'pushover',
                                                        'ntfy',
                                                        'gotify',
                                                        'pushplus',
                                                        'serverchan3',
                                                        'custom',
                                                        'discord',
                                                        'slack',
                                                        'astrbot'],
                              'delimiter': ','},
        'warning_codes': []},
    "NOTIFICATION_DEDUP_TTL_SECONDS": {       'category': 'notification',
        'data_type': 'integer',
        'default_value': '0',
        'description': 'Suppress duplicate static notifications with the same dedup key within this TTL. 0 disables '
                       'deduplication.',
        'display_order': 65,
        'docs': [       {       'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/notifications.md',
                                'label': '通知渠道与路由'}],
        'examples': ['NOTIFICATION_DEDUP_TTL_SECONDS=3600', 'NOTIFICATION_COOLDOWN_SECONDS=600'],
        'help_key': 'settings.notification.dedup',
        'is_editable': True,
        'is_required': False,
        'is_sensitive': False,
        'options': [],
        'title': 'Notification Dedup TTL Seconds',
        'ui_control': 'number',
        'validation': {'min': 0},
        'warning_codes': []},
    "NOTIFICATION_COOLDOWN_SECONDS": {       'category': 'notification',
        'data_type': 'integer',
        'default_value': '0',
        'description': 'Suppress repeated static notifications with the same cooldown key during this window. 0 '
                       'disables cooldown.',
        'display_order': 66,
        'docs': [       {       'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/notifications.md',
                                'label': '通知渠道与路由'}],
        'examples': ['NOTIFICATION_COOLDOWN_SECONDS=600', 'NOTIFICATION_DEDUP_TTL_SECONDS=3600'],
        'help_key': 'settings.notification.dedup',
        'is_editable': True,
        'is_required': False,
        'is_sensitive': False,
        'options': [],
        'title': 'Notification Cooldown Seconds',
        'ui_control': 'number',
        'validation': {'min': 0},
        'warning_codes': []},
    "NOTIFICATION_QUIET_HOURS": {       'category': 'notification',
        'data_type': 'string',
        'default_value': '',
        'description': 'Quiet window in HH:MM-HH:MM format. Supports overnight ranges. Empty disables quiet hours.',
        'display_order': 67,
        'docs': [       {       'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/notifications.md',
                                'label': '通知渠道与路由'}],
        'examples': ['NOTIFICATION_QUIET_HOURS=23:00-07:00', 'NOTIFICATION_TIMEZONE=Asia/Shanghai'],
        'help_key': 'settings.notification.quiet_hours',
        'is_editable': True,
        'is_required': False,
        'is_sensitive': False,
        'options': [],
        'title': 'Notification Quiet Hours',
        'ui_control': 'text',
        'validation': {'pattern': '^([01]\\d|2[0-3]):[0-5]\\d-([01]\\d|2[0-3]):[0-5]\\d$'},
        'warning_codes': []},
    "NOTIFICATION_TIMEZONE": {       'category': 'notification',
        'data_type': 'string',
        'default_value': '',
        'description': 'IANA timezone for quiet hours, e.g. Asia/Shanghai. Empty follows TZ or the local system '
                       'timezone.',
        'display_order': 68,
        'docs': [       {       'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/notifications.md',
                                'label': '通知渠道与路由'}],
        'examples': ['NOTIFICATION_TIMEZONE=Asia/Shanghai', 'NOTIFICATION_TIMEZONE=America/New_York'],
        'help_key': 'settings.notification.quiet_hours',
        'is_editable': True,
        'is_required': False,
        'is_sensitive': False,
        'options': [],
        'title': 'Notification Timezone',
        'ui_control': 'text',
        'validation': {'timezone': True},
        'warning_codes': []},
    "NOTIFICATION_MIN_SEVERITY": {       'category': 'notification',
        'data_type': 'string',
        'default_value': '',
        'description': 'Suppress static notifications below this severity. Empty keeps current behavior.',
        'display_order': 69,
        'docs': [       {       'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/notifications.md',
                                'label': '通知渠道与路由'}],
        'examples': ['NOTIFICATION_MIN_SEVERITY=warning', 'NOTIFICATION_MIN_SEVERITY='],
        'help_key': 'settings.notification.MIN_SEVERITY',
        'is_editable': True,
        'is_required': False,
        'is_sensitive': False,
        'options': [       {'label': 'Not set', 'value': ''},
                           {'label': 'info', 'value': 'info'},
                           {'label': 'warning', 'value': 'warning'},
                           {'label': 'error', 'value': 'error'},
                           {'label': 'critical', 'value': 'critical'}],
        'title': 'Notification Minimum Severity',
        'ui_control': 'select',
        'validation': {'enum': ['', 'info', 'warning', 'error', 'critical']},
        'warning_codes': []},
    "NOTIFICATION_DAILY_DIGEST_ENABLED": {       'category': 'notification',
        'data_type': 'boolean',
        'default_value': 'false',
        'description': 'Reserved P4 flag. It is visible for compatibility but does not send daily digests yet.',
        'display_order': 70,
        'docs': [       {       'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/notifications.md',
                                'label': '通知渠道与路由'}],
        'examples': ['NOTIFICATION_DAILY_DIGEST_ENABLED=false'],
        'help_key': 'settings.notification.DAILY_DIGEST_ENABLED',
        'is_editable': True,
        'is_required': False,
        'is_sensitive': False,
        'options': [],
        'title': 'Notification Daily Digest Enabled (Reserved)',
        'ui_control': 'switch',
        'validation': {},
        'warning_codes': ['reserved_flag']}
}
