"""
字段定义 - system 分类
从 config_registry.py 按 category 拆分
"""

FIELD_DEFINITIONS: dict = {
    "SCHEDULE_TIME": {       'category': 'system',
        'data_type': 'time',
        'default_value': '18:00',
        'description': 'Daily schedule time in HH:MM format.',
        'display_order': 10,
        'docs': [       {       'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/full-guide.md#其他配置',
                                'label': '完整指南：其他配置'}],
        'examples': ['SCHEDULE_TIME=18:00', 'SCHEDULE_ENABLED=true', 'SCHEDULE_RUN_IMMEDIATELY=false'],
        'help_key': 'settings.system.schedule',
        'is_editable': True,
        'is_required': False,
        'is_sensitive': False,
        'options': [],
        'title': 'Schedule Time',
        'ui_control': 'time',
        'validation': {'pattern': '^([01]\\d|2[0-3]):[0-5]\\d$'},
        'warning_codes': ['local_timezone']},
    "HTTP_PROXY": {       'category': 'system',
        'data_type': 'string',
        'default_value': None,
        'description': 'Optional HTTP proxy endpoint.',
        'display_order': 20,
        'docs': [       {       'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/full-guide.md#环境变量完整列表',
                                'label': '完整指南：环境变量完整列表'}],
        'examples': ['HTTP_PROXY=http://127.0.0.1:7890', 'HTTPS_PROXY=http://127.0.0.1:7890'],
        'help_key': 'settings.system.HTTP_PROXY',
        'is_editable': True,
        'is_required': False,
        'is_sensitive': False,
        'options': [],
        'title': 'HTTP Proxy',
        'ui_control': 'text',
        'validation': {},
        'warning_codes': ['network_scope']},
    "LOG_LEVEL": {       'category': 'system',
        'data_type': 'string',
        'default_value': 'INFO',
        'description': 'Application log level.',
        'display_order': 30,
        'docs': [       {       'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/full-guide.md#环境变量完整列表',
                                'label': '完整指南：环境变量完整列表'}],
        'examples': ['LOG_LEVEL=INFO', 'LOG_LEVEL=DEBUG'],
        'help_key': 'settings.system.LOG_LEVEL',
        'is_editable': True,
        'is_required': False,
        'is_sensitive': False,
        'options': ['DEBUG', 'INFO', 'WARNING', 'ERROR', 'CRITICAL'],
        'title': 'Log Level',
        'ui_control': 'select',
        'validation': {'enum': ['DEBUG', 'INFO', 'WARNING', 'ERROR', 'CRITICAL']},
        'warning_codes': ['restart_required']},
    "LOG_DIR": {       'category': 'system',
        'data_type': 'string',
        'default_value': './logs',
        'description': 'Directory for application logs. The runtime user or container must be able to write to this '
                       'path.',
        'display_order': 31,
        'docs': [       {       'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/full-guide.md#环境变量完整列表',
                                'label': '完整指南：环境变量完整列表'}],
        'examples': ['LOG_DIR=./logs', 'LOG_DIR=/app/logs'],
        'help_key': 'settings.system.LOG_DIR',
        'is_editable': True,
        'is_required': False,
        'is_sensitive': False,
        'options': [],
        'title': 'Log Directory',
        'ui_control': 'text',
        'validation': {},
        'warning_codes': ['restart_required', 'path_must_be_writable']},
    "WEBUI_ENABLED": {       'category': 'system',
        'data_type': 'boolean',
        'default_value': 'false',
        'description': 'Startup-time compatibility flag for default WebUI/API service mode. Saving this setting does '
                       'not start or stop the current process.',
        'display_order': 37,
        'docs': [       {       'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/full-guide.md#webui-与-api-服务',
                                'label': '完整指南：WebUI 与 API'},
                        {       'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/deploy-webui-cloud.md',
                                'label': '云服务器访问 WebUI'}],
        'examples': ['WEBUI_ENABLED=false', 'WEBUI_ENABLED=true'],
        'help_key': 'settings.system.WEBUI_ENABLED',
        'is_editable': True,
        'is_required': False,
        'is_sensitive': False,
        'options': [],
        'title': 'Web UI Enabled',
        'ui_control': 'switch',
        'validation': {},
        'warning_codes': ['restart_required']},
    "WEBUI_AUTO_BUILD": {       'category': 'system',
        'data_type': 'boolean',
        'default_value': 'true',
        'description': 'Build or verify the Web frontend assets before backend WebUI startup. Disable only when assets '
                       'are prebuilt.',
        'display_order': 38,
        'docs': [       {       'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/full-guide.md#webui-与-api-服务',
                                'label': '完整指南：WebUI 与 API'},
                        {       'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/deploy-webui-cloud.md',
                                'label': '云服务器访问 WebUI'}],
        'examples': ['WEBUI_AUTO_BUILD=true', 'WEBUI_AUTO_BUILD=false'],
        'help_key': 'settings.system.WEBUI_AUTO_BUILD',
        'is_editable': True,
        'is_required': False,
        'is_sensitive': False,
        'options': [],
        'title': 'Web UI Auto Build',
        'ui_control': 'switch',
        'validation': {},
        'warning_codes': ['restart_required', 'requires_built_web_assets']},
    "WEBUI_HOST": {       'category': 'system',
        'data_type': 'string',
        'default_value': '127.0.0.1',
        'description': 'Host address for Web UI service binding.',
        'display_order': 39,
        'docs': [       {       'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/deploy-webui-cloud.md',
                                'label': '云服务器访问 WebUI'},
                        {       'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/full-guide.md#webui-与-api-服务',
                                'label': '完整指南：WebUI 与 API'}],
        'examples': ['WEBUI_HOST=127.0.0.1', 'WEBUI_HOST=0.0.0.0'],
        'help_key': 'settings.system.WEBUI_HOST',
        'is_editable': True,
        'is_required': False,
        'is_sensitive': False,
        'options': [],
        'title': 'Web UI Host',
        'ui_control': 'text',
        'validation': {},
        'warning_codes': ['public_bind_requires_auth', 'restart_required']},
    "WEBUI_PORT": {       'category': 'system',
        'data_type': 'integer',
        'default_value': '8000',
        'description': 'Port for Web UI service.',
        'display_order': 40,
        'docs': [       {       'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/deploy-webui-cloud.md',
                                'label': '云服务器访问 WebUI'},
                        {       'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/full-guide.md#webui-与-api-服务',
                                'label': '完整指南：WebUI 与 API'}],
        'examples': ['WEBUI_PORT=8000', 'WEBUI_PORT=18000'],
        'help_key': 'settings.system.WEBUI_PORT',
        'is_editable': True,
        'is_required': False,
        'is_sensitive': False,
        'options': [],
        'title': 'Web UI Port',
        'ui_control': 'number',
        'validation': {'max': 65535, 'min': 1},
        'warning_codes': ['port_mapping_required', 'restart_required']},
    "RUN_IMMEDIATELY": {       'category': 'system',
        'data_type': 'boolean',
        'default_value': 'true',
        'description': 'Whether to run analysis immediately on startup (non-schedule mode).',
        'display_order': 45,
        'docs': [       {       'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/full-guide.md#其他配置',
                                'label': '完整指南：其他配置'}],
        'examples': ['RUN_IMMEDIATELY=true', 'RUN_IMMEDIATELY=false'],
        'help_key': 'settings.system.RUN_IMMEDIATELY',
        'is_editable': True,
        'is_required': False,
        'is_sensitive': False,
        'options': [],
        'title': 'Run Immediately',
        'ui_control': 'switch',
        'validation': {},
        'warning_codes': ['restart_required']},
    "SCHEDULE_ENABLED": {       'category': 'system',
        'data_type': 'boolean',
        'default_value': 'false',
        'description': 'Enable daily scheduled analysis run.',
        'display_order': 8,
        'docs': [       {       'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/full-guide.md#其他配置',
                                'label': '完整指南：其他配置'}],
        'examples': ['SCHEDULE_ENABLED=true', 'SCHEDULE_TIME=18:00', 'SCHEDULE_RUN_IMMEDIATELY=false'],
        'help_key': 'settings.system.schedule',
        'is_editable': True,
        'is_required': False,
        'is_sensitive': False,
        'options': [],
        'title': 'Schedule Enabled',
        'ui_control': 'switch',
        'validation': {},
        'warning_codes': ['restart_required']},
    "ADMIN_AUTH_ENABLED": {       'category': 'system',
        'data_type': 'boolean',
        'default_value': 'false',
        'description': 'Enable password protection for Web UI. The first visit initializes the admin password.',
        'display_order': 41,
        'docs': [       {       'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/full-guide.md#其他配置',
                                'label': '完整指南：其他配置'},
                        {       'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/deploy-webui-cloud.md',
                                'label': '云服务器访问 WebUI'}],
        'examples': ['ADMIN_AUTH_ENABLED=true', 'python -m src.auth reset_password'],
        'help_key': 'settings.system.ADMIN_AUTH_ENABLED',
        'is_editable': False,
        'is_required': False,
        'is_sensitive': False,
        'options': [],
        'title': 'Admin Auth Enabled',
        'ui_control': 'switch',
        'validation': {},
        'warning_codes': ['public_webui_requires_auth', 'auth_settings_endpoint_required']},
    "TRUST_X_FORWARDED_FOR": {       'category': 'system',
        'data_type': 'boolean',
        'default_value': 'false',
        'description': 'Use X-Forwarded-For as the client IP behind one trusted reverse proxy.',
        'display_order': 42,
        'docs': [       {       'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/full-guide.md#其他配置',
                                'label': '完整指南：其他配置'},
                        {       'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/deploy-webui-cloud.md',
                                'label': '云服务器访问 WebUI'}],
        'examples': ['TRUST_X_FORWARDED_FOR=false', 'TRUST_X_FORWARDED_FOR=true'],
        'help_key': 'settings.system.TRUST_X_FORWARDED_FOR',
        'is_editable': True,
        'is_required': False,
        'is_sensitive': False,
        'options': [],
        'title': 'Trust X-Forwarded-For',
        'ui_control': 'switch',
        'validation': {},
        'warning_codes': ['trusted_proxy_only']},
    "SCHEDULE_RUN_IMMEDIATELY": {       'category': 'system',
        'data_type': 'boolean',
        'default_value': 'true',
        'description': 'Whether to run one analysis immediately on startup in schedule mode.',
        'display_order': 11,
        'docs': [       {       'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/full-guide.md#其他配置',
                                'label': '完整指南：其他配置'}],
        'examples': ['SCHEDULE_RUN_IMMEDIATELY=true', 'SCHEDULE_RUN_IMMEDIATELY=false'],
        'help_key': 'settings.system.schedule',
        'is_editable': True,
        'is_required': False,
        'is_sensitive': False,
        'options': [],
        'title': 'Schedule Run Immediately',
        'ui_control': 'switch',
        'validation': {},
        'warning_codes': ['restart_required']},
    "TRADING_DAY_CHECK_ENABLED": {       'category': 'system',
        'data_type': 'boolean',
        'default_value': 'true',
        'description': 'Skip analysis on non-trading days. Set to false or use --force-run to override.',
        'display_order': 12,
        'docs': [       {       'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/full-guide.md#其他配置',
                                'label': '完整指南：其他配置'}],
        'examples': ['TRADING_DAY_CHECK_ENABLED=true', 'TRADING_DAY_CHECK_ENABLED=false'],
        'help_key': 'settings.system.TRADING_DAY_CHECK_ENABLED',
        'is_editable': True,
        'is_required': False,
        'is_sensitive': False,
        'options': [],
        'title': 'Trading Day Check',
        'ui_control': 'switch',
        'validation': {},
        'warning_codes': ['force_run_override']},
    "MARKET_REVIEW_ENABLED": {       'category': 'system',
        'data_type': 'boolean',
        'default_value': 'true',
        'description': 'Enable market overview/review in analysis reports.',
        'display_order': 46,
        'docs': [       {       'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/full-guide.md#环境变量完整列表',
                                'label': '完整指南：环境变量完整列表'}],
        'examples': ['MARKET_REVIEW_ENABLED=true', 'MARKET_REVIEW_REGION=cn'],
        'help_key': 'settings.system.market_review',
        'is_editable': True,
        'is_required': False,
        'is_sensitive': False,
        'options': [],
        'title': 'Market Review Enabled',
        'ui_control': 'switch',
        'validation': {},
        'warning_codes': []},
    "MARKET_REVIEW_REGION": {       'category': 'system',
        'data_type': 'string',
        'default_value': 'cn',
        'description': 'Market region for review: cn (A-shares), hk (Hong Kong), us (US stocks), or both (all '
                       'markets).',
        'display_order': 47,
        'docs': [       {       'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/full-guide.md#环境变量完整列表',
                                'label': '完整指南：环境变量完整列表'}],
        'examples': ['MARKET_REVIEW_REGION=cn', 'MARKET_REVIEW_REGION=both'],
        'help_key': 'settings.system.market_review',
        'is_editable': True,
        'is_required': False,
        'is_sensitive': False,
        'options': ['cn', 'hk', 'us', 'both'],
        'title': 'Market Review Region',
        'ui_control': 'select',
        'validation': {'enum': ['cn', 'hk', 'us', 'both']},
        'warning_codes': []},
    "MARKET_REVIEW_COLOR_SCHEME": {       'category': 'system',
        'data_type': 'string',
        'default_value': 'green_up',
        'description': 'Index change color style in market-review tables: green_up (green for gains, red for losses) '
                       'or red_up (red for gains, green for losses).',
        'display_order': 48,
        'docs': [       {       'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/full-guide.md#环境变量完整列表',
                                'label': '完整指南：环境变量完整列表'}],
        'examples': ['MARKET_REVIEW_COLOR_SCHEME=green_up', 'MARKET_REVIEW_COLOR_SCHEME=red_up'],
        'help_key': 'settings.system.market_review',
        'is_editable': True,
        'is_required': False,
        'is_sensitive': False,
        'options': [       {'label': 'Green Up / Red Down', 'value': 'green_up'},
                           {'label': 'Red Up / Green Down', 'value': 'red_up'}],
        'title': 'Market Review Color Scheme',
        'ui_control': 'select',
        'validation': {'enum': ['green_up', 'red_up']},
        'warning_codes': []},
    "MAX_WORKERS": {       'category': 'system',
        'data_type': 'integer',
        'default_value': '3',
        'description': 'Maximum concurrent analysis threads. Keep low to avoid API rate limits.',
        'display_order': 50,
        'docs': [       {       'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/full-guide.md#环境变量完整列表',
                                'label': '完整指南：环境变量完整列表'}],
        'examples': ['MAX_WORKERS=3', 'MAX_WORKERS=5'],
        'help_key': 'settings.system.MAX_WORKERS',
        'is_editable': True,
        'is_required': False,
        'is_sensitive': False,
        'options': [],
        'title': 'Max Workers',
        'ui_control': 'number',
        'validation': {'max': 20, 'min': 1},
        'warning_codes': []},
    "ANALYSIS_DELAY": {       'category': 'system',
        'data_type': 'number',
        'default_value': '0',
        'description': 'Delay in seconds between individual stock analyses (for API rate limiting).',
        'display_order': 51,
        'docs': [       {       'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/full-guide.md#环境变量完整列表',
                                'label': '完整指南：环境变量完整列表'}],
        'examples': ['ANALYSIS_DELAY=0', 'ANALYSIS_DELAY=5'],
        'help_key': 'settings.system.ANALYSIS_DELAY',
        'is_editable': True,
        'is_required': False,
        'is_sensitive': False,
        'options': [],
        'title': 'Analysis Delay',
        'ui_control': 'number',
        'validation': {'max': 60, 'min': 0},
        'warning_codes': []},
    "DEBUG": {       'category': 'system',
        'data_type': 'boolean',
        'default_value': 'false',
        'description': 'Enable debug mode with verbose logging.',
        'display_order': 55,
        'docs': [       {       'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/full-guide.md#环境变量完整列表',
                                'label': '完整指南：环境变量完整列表'}],
        'examples': ['DEBUG=true', 'DEBUG=false'],
        'help_key': 'settings.system.DEBUG',
        'is_editable': True,
        'is_required': False,
        'is_sensitive': False,
        'options': [],
        'title': 'Debug Mode',
        'ui_control': 'switch',
        'validation': {},
        'warning_codes': []}
}
